# Based off https://github.com/getsentry/sentry/blob/master/.github/file-filters.yml

api_changes:
  - "snuba/datasets/configuration/**/*.yaml"
  - "snuba/web/*.py"
  - "snuba/query/**/*.py"
  - "snuba/snuba_migrations/**/*"
  - "snuba/cli/devserver.py"
