migrations:
  - changed-files:
    - any-glob-to-any-file: snuba/migrations/group_loader.py
    - any-glob-to-any-file: snuba/migrations/groups.py
    - any-glob-to-any-file: snuba/snuba_migrations/**/*
    - any-glob-to-any-file: snuba/migrations/system_migrations/*
