minVersion: "0.27.2"
changelogPolicy: auto
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
    - 'build-amd64'
    - 'build-arm64'
    - 'assemble'
targets:
- id: release
  name: docker
  source: ghcr.io/getsentry/snuba
  target: getsentry/snuba
- id: latest
  name: docker
  source: ghcr.io/getsentry/snuba
  target: getsentry/snuba
  targetFormat: '{{{target}}}:latest'
- name: github
versioning:
  policy: calver
