minVersion: "2.15.0"
changelog:
  policy: auto
artifactProvider:
  name: none
statusProvider:
  name: github
  config:
    contexts:
    - 'build-amd64'
    - 'build-arm64'
    - 'assemble'
targets:
  - id: release
    name: docker
    source: ghcr.io/getsentry/snuba
    target: ghcr.io/getsentry/snuba
  - id: latest
    name: docker
    source: ghcr.io/getsentry/snuba
    target: ghcr.io/getsentry/snuba
    targetFormat: '{{{target}}}:latest'
  - name: github
versioning:
  policy: calver  