sentry:
  organization: sentry
  project: snuba
  repository: getsentry/snuba

steps:
  - kind: KubernetesDeployment
    selector:
      label_selector: service=snuba
    containers:
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: api
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: errors-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: errors-replacer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: replacer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: transactions-consumer-new
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: outcomes-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: loadbalancer-outcomes-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: outcomes-billing-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: events-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: events-subscriptions-executor
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: transactions-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: transactions-subscriptions-executor
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: querylog-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: snuba-admin
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: metrics-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-sets-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-distributions-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-counters-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: metrics-counters-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: metrics-sets-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: metrics-subscriptions-executor
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-sets-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-distributions-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-counters-subscriptions-scheduler
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-sets-subscriptions-executor
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-distributions-subscriptions-executor
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-counters-subscriptions-executor
  - kind: KubernetesCronJob
    selector:
      label_selector: service=snuba
    containers:
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: cleanup
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: optimize
