# sentry:
#   organization: sentry
#   project: snuba
#   repository: getsentry/snuba

steps:
- kind: KubernetesDeployment
  selector:
    label_selector: service=snuba
  containers:
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: api
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: errors-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: errors-replacer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: replacer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: transactions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: spans-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: sessions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: outcomes-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadbalancer-outcomes-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: outcomes-billing-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: events-subscriptions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: events-subscriptions-scheduler
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: events-subscriptions-executor
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: transactions-subscriptions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: sessions-subscriptions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: cdc-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: cdc-groupassignee-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: querylog-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: snuba-admin
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: metrics-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadtest-errors-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadtest-sessions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadtest-transactions-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadtest-outcomes-consumer
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: loadtest-loadbalancer-outcomes-consumer
- kind: KubernetesCronJob
  selector:
    label_selector: service=snuba
  containers:
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: cleanup
  - image: us.gcr.io/sentryio/snuba:{sha}
    name: optimize
