sentry:
  organization: sentry
  project: snuba
  repository: getsentry/snuba

steps:
  - kind: KubernetesDeployment
    selector:
      label_selector: service=snuba
    containers:
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-sets-consumer
      - image: us.gcr.io/sentryio/snuba:{sha}
        name: generic-metrics-distributions-consumer
