# sentry:
#   organization: sentry
#   project: snuba
#   repository: getsentry/snuba

kubernetes:
  credentials:
    kind: gcloud
    project: internal-sentry
    cluster: primary
    zone: us-central1-b

steps:
- kind: KubernetesDeployment
  selector:
    label_selector: service=snuba,environment={environment}
  containers:
  - image: us.gcr.io/internal-sentry/github-getsentry-snuba:{sha}
    name: api
  - image: us.gcr.io/internal-sentry/github-getsentry-snuba:{sha}
    name: consumer
  - image: us.gcr.io/internal-sentry/github-getsentry-snuba:{sha}
    name: replacer
- kind: KubernetesCronJob
  selector:
    label_selector: service=snuba,environment={environment}
  containers:
  - image: us.gcr.io/internal-sentry/github-getsentry-snuba:{sha}
    name: cleanup
  - image: us.gcr.io/internal-sentry/github-getsentry-snuba:{sha}
    name: optimize
