steps:
  - name: "gcr.io/kaniko-project/executor:v1.16.0"
    id: runtime-image
    waitFor: ["-"]
    args:
      [
        "--cache=true",
        "--use-new-run",
        "--build-arg",
        "SOURCE_COMMIT=$COMMIT_SHA",
        "--destination=us-central1-docker.pkg.dev/$PROJECT_ID/snuba/image:$COMMIT_SHA-cloudbuild",
        "--target=application",
        "-f",
        "./Dockerfile",
      ]
    timeout: 2400s

  # Pull docker image again, so we can get build info.
  # https://github.com/GoogleCloudPlatform/cloud-builders-community/issues/212#issuecomment-1478828752
  - name: docker
    args: [pull, "us-central1-docker.pkg.dev/$PROJECT_ID/snuba/image:$COMMIT_SHA-cloudbuild"]

# This is needed for Freight to find matching builds
images: [
    'us-central1-docker.pkg.dev/$PROJECT_ID/snuba/image:$COMMIT_SHA-cloudbuild',
]
timeout: 2640s
options:
  # We need more memory for Webpack builds & e2e self-hosted tests
  machineType: "E2_HIGHCPU_32"
