steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker pull us.gcr.io/$PROJECT_ID/$REPO_NAME:latest || true',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
            '-t', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
            '--build-arg', 'SNUBA_VERSION_SHA=$COMMIT_SHA',
            '--cache-from', 'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
            '.'
        ]
images: [
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:latest',
  'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  ]
timeout: 3600s
logsBucket: 'gs://sentryio-cloudbuild-logs'
