steps:
  - name: "gcr.io/kaniko-project/executor:v1.16.0"
    id: runtime-image
    waitFor: ["-"]
    args:
      [
        "--cache=true",
        "--use-new-run",
        "--build-arg",
        "SOURCE_COMMIT=$COMMIT_SHA",
        "--destination=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--target=application",
        "-f",
        "./Dockerfile",
      ]
    timeout: 1200s


  # Pull docker image again, so we can get build info.
  # https://github.com/GoogleCloudPlatform/cloud-builders-community/issues/212#issuecomment-1478828752
  - name: docker
    args: [pull, "us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]


# This is needed for Freight to find matching builds
images: ['us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
timeout: 2640s
options:
  # We need more memory for Webpack builds & e2e self-hosted tests
  machineType: "E2_HIGHCPU_8"
  env:
    - "CI=1"
    - "SNUBA_IMAGE=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    - "DOCKER_REPO=getsentry/snuba"
    - "SENTRY_TEST_HOST=http://nginx"
