steps:
  - name: "gcr.io/kaniko-project/executor:v1.5.1"
    id: runtime-image
    waitFor: ["-"]
    args:
      [
        "--cache=true",
        "--use-new-run",
        "--build-arg",
        "SOURCE_COMMIT=$COMMIT_SHA",
        "--destination=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "-f",
        "./Dockerfile",
      ]
    timeout: 180s
  # Unit tests
  - name: "gcr.io/$PROJECT_ID/docker-compose"
    id: unit-tests
    waitFor:
      - runtime-image
    args:
      - "-f"
      - "docker-compose.gcb.yml"
      - run
      - "--rm"
      - snuba-test
    env:
      - 'SNUBA_SETTINGS=test'
  # Clean up after tests
  - name: "gcr.io/$PROJECT_ID/docker-compose"
    id: unit-tests-cleanup
    waitFor:
      - unit-tests
    args:
      - "-f"
      - "docker-compose.gcb.yml"
      - down
      - "--rmi"
      - "local"
      - "-v"
      - "--remove-orphans"

# This is needed for Freight to find matching builds
images: ['us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
timeout: 2640s
options:
  # We need more memory for Webpack builds & e2e self-hosted tests
  machineType: "E2_HIGHCPU_8"
  env:
    - "CI=1"
    - "SNUBA_IMAGE=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
    - "DOCKER_REPO=getsentry/snuba"
    - "SENTRY_TEST_HOST=http://nginx"
