ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION}-slim

# these are required all the way through, and removing them will cause bad things
WORKDIR /usr/src/snuba

ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on

# Install dependencies first because requirements.txt is way less likely to be changed.
COPY requirements.txt ./
RUN set -ex; \
    \
    buildDeps=' \
        gcc \
        libc6-dev \
        liblz4-dev \
    '; \
    apt-get update; \
    apt-get install -y $buildDeps --no-install-recommends; \
    \
    pip install -r requirements.txt; \
    \
    apt-get purge -y --auto-remove $buildDeps; \
    rm -rf /var/lib/apt/lists/*;

# Layer cache is pretty much invalidated here all the time,
# so try not to do anything heavy beyond here.
COPY . ./
RUN set -ex; \
    groupadd -r snuba; \
    useradd -r -g snuba snuba; \
    chown -R snuba:snuba ./; \
    pip install -e .; \
    snuba --help;

ENV FLASK_DEBUG=0 \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

EXPOSE 1218
ENTRYPOINT [ "./docker_entrypoint.sh" ]
CMD [ "api" ]
