FunctionCall(
    None,
    "and",
    tuple(
        [
            FunctionCall(
                None,
                "greaterOrEquals",
                tuple(
                    [
                        Column("_snuba_timestamp", None, "timestamp"),
                        Literal(None, datetime.datetime(2021, 7, 12, 19, 45, 1)),
                    ]
                ),
            ),
            FunctionCall(
                None,
                "and",
                tuple(
                    [
                        FunctionCall(
                            None,
                            "less",
                            tuple(
                                [
                                    Column("_snuba_timestamp", None, "timestamp"),
                                    Literal(
                                        None, datetime.datetime(2021, 8, 11, 19, 45, 1),
                                    ),
                                ]
                            ),
                        ),
                        FunctionCall(
                            None,
                            "and",
                            tuple(
                                [
                                    FunctionCall(
                                        None,
                                        "in",
                                        tuple(
                                            [
                                                Column(
                                                    "_snuba_project_id",
                                                    None,
                                                    "project_id",
                                                ),
                                                FunctionCall(
                                                    None,
                                                    "tuple",
                                                    tuple([Literal(None, 300688)]),
                                                ),
                                            ]
                                        ),
                                    ),
                                    FunctionCall(
                                        None,
                                        "and",
                                        tuple(
                                            [
                                                FunctionCall(
                                                    None,
                                                    "notEquals",
                                                    tuple(
                                                        [
                                                            FunctionCall(
                                                                None,
                                                                "ifNull",
                                                                tuple(
                                                                    [
                                                                        FunctionCall(
                                                                            "_snuba_tags[duration_group]",
                                                                            "arrayElement",
                                                                            tuple(
                                                                                [
                                                                                    Column(
                                                                                        None,
                                                                                        None,
                                                                                        "tags.value",
                                                                                    ),
                                                                                    FunctionCall(
                                                                                        None,
                                                                                        "indexOf",
                                                                                        tuple(
                                                                                            [
                                                                                                Column(
                                                                                                    None,
                                                                                                    None,
                                                                                                    "tags.key",
                                                                                                ),
                                                                                                Literal(
                                                                                                    None,
                                                                                                    "duration_group",
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                ]
                                                                            ),
                                                                        ),
                                                                        Literal(
                                                                            None, ""
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            Literal(None, ""),
                                                        ]
                                                    ),
                                                ),
                                                FunctionCall(
                                                    None,
                                                    "equals",
                                                    tuple(
                                                        [
                                                            FunctionCall(
                                                                None,
                                                                "ifNull",
                                                                tuple(
                                                                    [
                                                                        FunctionCall(
                                                                            "_snuba_tags[duration_group]",
                                                                            "arrayElement",
                                                                            tuple(
                                                                                [
                                                                                    Column(
                                                                                        None,
                                                                                        None,
                                                                                        "tags.value",
                                                                                    ),
                                                                                    FunctionCall(
                                                                                        None,
                                                                                        "indexOf",
                                                                                        tuple(
                                                                                            [
                                                                                                Column(
                                                                                                    None,
                                                                                                    None,
                                                                                                    "tags.key",
                                                                                                ),
                                                                                                Literal(
                                                                                                    None,
                                                                                                    "duration_group",
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                ]
                                                                            ),
                                                                        ),
                                                                        Literal(
                                                                            None, ""
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            Literal(None, "<10s"),
                                                        ]
                                                    ),
                                                ),
                                            ]
                                        ),
                                    ),
                                ]
                            ),
                        ),
                    ]
                ),
            ),
        ]
    ),
)
