raw_event = {
    "culprit": "io.sentry.example.Application in main",
    "organization_id": 3,
    "errors": [],
    "title": "Exception!",
    "extra": {"Sentry-Threadname": "io.sentry.example.Application.main()"},
    "fingerprint": ["{{ default }}"],
    "id": "bce76c2473324fa387b33564eacf34a0",
    "key_id": 113866,
    "message": "Caught exception!",
    "metadata": {"type": "ArithmeticException", "value": "/ by zero"},
    "platform": "java",
    "project": 156,
    "release": "1.0",
    "dist": None,
    "sdk": {
        "integrations": ["logback"],
        "name": "sentry-java",
        "version": "1.6.1-d1e3a",
    },
    "contexts": {"device": {"online": True, "charging": True, "model_id": "Galaxy"}},
    "sentry.interfaces.Exception": {
        "exc_omitted": None,
        "values": [
            {
                "module": "java.lang",
                "mechanism": {
                    "type": "promise",
                    "description": "globally unhandled promise rejection",
                    "help_link": "http://example.com",
                    "handled": False,
                    "data": {"polyfill": "Bluebird"},
                    "meta": {"errno": {"number": 123112, "name": ""}},
                },
                "stacktrace": {
                    "frames": [
                        {
                            "abs_path": "Thread.java",
                            "filename": "Thread.java",
                            "function": "run",
                            "in_app": False,
                            "lineno": 748,
                            "module": "java.lang.Thread",
                        },
                        {
                            "abs_path": "ExecJavaMojo.java",
                            "filename": "ExecJavaMojo.java",
                            "function": "run",
                            "in_app": False,
                            "lineno": 293,
                            "module": "org.codehaus.mojo.exec.ExecJavaMojo$1",
                        },
                        {
                            "abs_path": "Method.java",
                            "filename": "Method.java",
                            "function": "invoke",
                            "in_app": False,
                            "lineno": 498,
                            "module": "java.lang.reflect.Method",
                        },
                        {
                            "abs_path": "DelegatingMethodAccessorImpl.java",
                            "filename": "DelegatingMethodAccessorImpl.java",
                            "function": "invoke",
                            "in_app": False,
                            "lineno": 43,
                            "module": "sun.reflect.DelegatingMethodAccessorImpl",
                        },
                        {
                            "abs_path": "NativeMethodAccessorImpl.java",
                            "filename": "NativeMethodAccessorImpl.java",
                            "function": "invoke",
                            "in_app": False,
                            "lineno": 62,
                            "module": "sun.reflect.NativeMethodAccessorImpl",
                        },
                        {
                            "abs_path": "NativeMethodAccessorImpl.java",
                            "filename": "NativeMethodAccessorImpl.java",
                            "function": "invoke0",
                            "in_app": False,
                            "module": "sun.reflect.NativeMethodAccessorImpl",
                        },
                        {
                            "abs_path": "Application.java",
                            "filename": "Application.java",
                            "function": "main",
                            "in_app": True,
                            "lineno": 17,
                            "module": "io.sentry.example.Application",
                        },
                    ]
                },
                "type": "ArithmeticException",
                "value": "/ by zero",
            }
        ],
    },
    "sentry.interfaces.Message": {"message": "Caught exception!"},
    "tags": [
        ["logger", "example.Application"],
        ["server_name", "localhost.localdomain"],
        ["level", "error"],
        ["custom_tag", "custom_value"],
    ],
    "time_spent": None,
    "type": "error",
    "version": "6",
}
