clusters:
  - host: 127.0.0.1
    port: 9000
    user: default
    password: ""
    http_port: 8123
    storage_sets:
      - "cdc"
      - "discover"
      - "events"
      - "events_ro"
      - "metrics"
      - "migrations"
      - "outcomes"
      - "querylog"
      - "sessions"
      - "transactions"
      - "profiles"
      - "functions"
      - "replays"
      - "generic_metrics_sets"
      - "generic_metrics_distributions"
      - "search_issues"
      - "generic_metrics_counters"

broker_config:
  bootstrap.servers: 127.0.0.1:9092
  security.protocol: plaintext
  ssl.ca.location: ""
  ssl.certificate.location: ""
  ssl.key.location: ""
  sasl.mechanism: null
  sasl.username: null
  sasl.password: null
