#!/usr/bin/env bash

red="$(tput setaf 1)"
bold="$(tput bold)"
reset="$(tput sgr0)"


files_changed_upstream="$(mktemp)"
trap "rm -f ${files_changed_upstream}" EXIT

git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD > "$files_changed_upstream"

grep -E --quiet 'requirements.txt' "$files_changed_upstream" && needs_py_update=1

grep -E --quiet 'migrations/groups.py' "$files_changed_upstream" && needs_update=1

[[ "$needs_update" ]] && cat <<EOF

[${red}${bold}!!!${reset}] Some migrations have changed, you may need to run:

  snuba migrations migrate --force

EOF

[[ "$needs_py_update" ]] && cat <<EOF

[${red}${bold}!!!${reset}] Python dependencies updated, you may need to run:

  make install-python-dependencies

EOF
