# Run a GoCD pipeline in the search-and-storage GCP project.
# The GoCD server is deployed in the gocd namespace. See https://github.com/getsentry/sns-gcloud/tree/main/ops
# for more details
#
# To access the server locally:
# kubectl port-forward --namespace gocd $(kubectl get pod -A --selector="app=gocd,component=server,release=gocd-app" --output jsonpath='{.items[0].metadata.name}') 8080:8153
#
# Server will be available on localhost:8080
format_version: 10
pipelines:
    deploy-snuba-sns-test:
        environment_variables:
            GCP_PROJECT: search-and-storage
            GKE_CLUSTER: sns-cluster-snuba
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: a
            GKE_BASTION_ZONE: a
            MIGRATIONS_READINESS: complete
        group: snuba
        lock_behavior: unlockWhenFinished
        materials:
            snuba_repo:
                git: https://github.com/getsentry/snuba.git
                shallow_clone: false
                branch: master
                destination: snuba
        stages:
            - checks:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      checks-migrations:
                          timeout: 1800
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    deploy_sha=`snuba/scripts/fetch_service_refs.py --pipeline "deploy-snuba-sns-test"` && \
                                    snuba/scripts/check-migrations.py --to $deploy_sha --workdir snuba
            - deploy:
                  fetch_materials: true
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                    --label-selector="service=snuba" \
                                    --image="ghcr.io/getsentry/snuba-ci:${GO_REVISION_SNUBA_REPO}" \
                                    --container-name="api" \
                                    --container-name="consumer" \
                                    --container-name="errors-consumer" \
                                    --container-name="errors-replacer" \
                                    --container-name="events-subscriptions-executor" \
                                    --container-name="events-subscriptions-scheduler" \
                                    --container-name="generic-metrics-counters-consumer" \
                                    --container-name="generic-metrics-counters-subscriptions-executor" \
                                    --container-name="generic-metrics-counters-subscriptions-scheduler" \
                                    --container-name="generic-metrics-distributions-consumer" \
                                    --container-name="generic-metrics-distributions-subscriptions-executor" \
                                    --container-name="generic-metrics-distributions-subscriptions-scheduler" \
                                    --container-name="generic-metrics-sets-consumer" \
                                    --container-name="generic-metrics-sets-subscriptions-executor" \
                                    --container-name="generic-metrics-sets-subscriptions-scheduler" \
                                    --container-name="loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-errors-consumer" \
                                    --container-name="loadtest-loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-outcomes-consumer" \
                                    --container-name="loadtest-transactions-consumer" \
                                    --container-name="metrics-consumer" \
                                    --container-name="metrics-counters-subscriptions-scheduler" \
                                    --container-name="metrics-sets-subscriptions-scheduler" \
                                    --container-name="metrics-subscriptions-executor" \
                                    --container-name="outcomes-billing-consumer" \
                                    --container-name="outcomes-consumer" \
                                    --container-name="profiles-consumer" \
                                    --container-name="profiling-functions-consumer" \
                                    --container-name="querylog-consumer" \
                                    --container-name="replacer" \
                                    --container-name="replays-consumer" \
                                    --container-name="search-issues-consumer" \
                                    --container-name="snuba-admin" \
                                    --container-name="transactions-consumer-new" \
                                    --container-name="transactions-subscriptions-executor" \
                                    --container-name="transactions-subscriptions-scheduler" \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=snuba" \
                                    --image="us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    --type="cronjob" \
                                    --container-name="cleanup" \
                                    --container-name="optimize"

            - migrate:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      migrate:
                          timeout: 1200
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-spawn-job.py \
                                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                    --label-selector="service=snuba-admin" \
                                    --container-name="snuba-admin" \
                                    "snuba-migrate" "ghcr.io/getsentry/snuba-ci:${GO_REVISION_SNUBA_REPO}" \
                                    -- snuba migrations migrate -r ${MIGRATIONS_READINESS}
                              - plugin:
                                    options:
                                        script: |
                                            /devinfra/scripts/k8s/k8stunnel \
                                            && /devinfra/scripts/k8s/k8s-spawn-job.py \
                                            --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                            --label-selector="service=snuba-admin" \
                                            --container-name="snuba-admin" \
                                            "snuba-migrate-reverse" "ghcr.io/getsentry/snuba-ci:${GO_REVISION_SNUBA_REPO}" \
                                            -- snuba migrations reverse-in-progress
                                    run_if: failed
                                    configuration:
                                        id: script-executor
                                        version: 1
