# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-snuba:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
            # Required for checkruns.
            GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
            GOCD_ACCESS_TOKEN: "{{SECRET:[devinfra][gocd_access_token]}}"
        group: snuba
        lock_behavior: unlockWhenFinished
        materials:
            snuba_repo:
                git: git@github.com:getsentry/snuba.git
                shallow_clone: false
                branch: master
                destination: snuba
        stages:
            - checks:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      checks:
                          timeout: 1800
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                    getsentry/snuba \
                                    ${GO_REVISION_SNUBA_REPO} \
                                    "Tests and code coverage (test)" \
                                    "Tests and code coverage (test_distributed)" \
                                    "Tests and code coverage (test_distributed_migrations)" \
                                    "Dataset Config Validation" \
                                    "sentry (0)" \
                                    "sentry (1)" \
                                    "self-hosted-end-to-end"
                              - script: |
                                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_SNUBA_REPO} \
                                    sentryio \
                                    "us.gcr.io/sentryio/snuba"
                              - script: |
                                    deploy_sha=`snuba/scripts/fetch_service_refs.py --pipeline "deploy-snuba"` && \
                                    snuba/scripts/check-migrations.py --to $deploy_sha --workdir snuba
            - deploy-canary:
                  fetch_materials: true
                  jobs:
                      create-sentry-release:
                          environment_variables:
                              SENTRY_ORG: sentry
                              SENTRY_PROJECT: snuba
                              SENTRY_AUTH_TOKEN: "{{SECRET:[devinfra-sentryio][token]}}"
                          timeout: 300
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    sentry-cli releases new "${GO_REVISION_SNUBA_REPO}"
                                    sentry-cli releases set-commits "${GO_REVISION_SNUBA_REPO}" --commit "getsentry/snuba@${GO_REVISION_SNUBA_REPO}"
                                    sentry-cli releases deploys "${GO_REVISION_SNUBA_REPO}" new -e canary
                      deploy-canary:
                          timeout: 1200
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                    --label-selector="service=snuba,is_canary=true" \
                                    --image="us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    --container-name="api" \
                                    --container-name="consumer" \
                                    --container-name="errors-consumer" \
                                    --container-name="errors-replacer" \
                                    --container-name="events-subscriptions-executor" \
                                    --container-name="events-subscriptions-scheduler" \
                                    --container-name="generic-metrics-counters-consumer" \
                                    --container-name="generic-metrics-counters-subscriptions-executor" \
                                    --container-name="generic-metrics-counters-subscriptions-scheduler" \
                                    --container-name="generic-metrics-distributions-consumer" \
                                    --container-name="generic-metrics-distributions-subscriptions-executor" \
                                    --container-name="generic-metrics-distributions-subscriptions-scheduler" \
                                    --container-name="generic-metrics-sets-consumer" \
                                    --container-name="generic-metrics-sets-subscriptions-executor" \
                                    --container-name="generic-metrics-sets-subscriptions-scheduler" \
                                    --container-name="loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-errors-consumer" \
                                    --container-name="loadtest-loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-outcomes-consumer" \
                                    --container-name="loadtest-transactions-consumer" \
                                    --container-name="metrics-consumer" \
                                    --container-name="metrics-counters-subscriptions-scheduler" \
                                    --container-name="metrics-sets-subscriptions-scheduler" \
                                    --container-name="metrics-subscriptions-executor" \
                                    --container-name="outcomes-billing-consumer" \
                                    --container-name="outcomes-consumer" \
                                    --container-name="profiles-consumer" \
                                    --container-name="profiling-functions-consumer" \
                                    --container-name="querylog-consumer" \
                                    --container-name="replacer" \
                                    --container-name="replays-consumer" \
                                    --container-name="search-issues-consumer" \
                                    --container-name="snuba-admin" \
                                    --container-name="transactions-consumer-new" \
                                    --container-name="transactions-subscriptions-executor" \
                                    --container-name="transactions-subscriptions-scheduler" \
                                    --container-name="spans-consumer" \
                                    --container-name="dlq-consumer" \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=snuba,is_canary=true" \
                                    --image="us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    --type="cronjob" \
                                    --container-name="cleanup" \
                                    --container-name="optimize"
            - deploy:
                  fetch_materials: true
                  jobs:
                      create-sentry-release:
                          environment_variables:
                              SENTRY_ORG: sentry
                              SENTRY_PROJECT: snuba
                              SENTRY_AUTH_TOKEN: "{{SECRET:[devinfra-sentryio][token]}}"
                          timeout: 300
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    sentry-cli releases deploys "${GO_REVISION_SNUBA_REPO}" new -e production
                                    sentry-cli releases finalize "${GO_REVISION_SNUBA_REPO}"
                      deploy:
                          timeout: 1200
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                    --label-selector="service=snuba" \
                                    --image="us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    --container-name="api" \
                                    --container-name="consumer" \
                                    --container-name="errors-consumer" \
                                    --container-name="errors-replacer" \
                                    --container-name="events-subscriptions-executor" \
                                    --container-name="events-subscriptions-scheduler" \
                                    --container-name="generic-metrics-counters-consumer" \
                                    --container-name="generic-metrics-counters-subscriptions-executor" \
                                    --container-name="generic-metrics-counters-subscriptions-scheduler" \
                                    --container-name="generic-metrics-distributions-consumer" \
                                    --container-name="generic-metrics-distributions-subscriptions-executor" \
                                    --container-name="generic-metrics-distributions-subscriptions-scheduler" \
                                    --container-name="generic-metrics-sets-consumer" \
                                    --container-name="generic-metrics-sets-subscriptions-executor" \
                                    --container-name="generic-metrics-sets-subscriptions-scheduler" \
                                    --container-name="loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-errors-consumer" \
                                    --container-name="loadtest-loadbalancer-outcomes-consumer" \
                                    --container-name="loadtest-outcomes-consumer" \
                                    --container-name="loadtest-transactions-consumer" \
                                    --container-name="metrics-consumer" \
                                    --container-name="metrics-counters-subscriptions-scheduler" \
                                    --container-name="metrics-sets-subscriptions-scheduler" \
                                    --container-name="metrics-subscriptions-executor" \
                                    --container-name="outcomes-billing-consumer" \
                                    --container-name="outcomes-consumer" \
                                    --container-name="profiles-consumer" \
                                    --container-name="profiling-functions-consumer" \
                                    --container-name="querylog-consumer" \
                                    --container-name="replacer" \
                                    --container-name="replays-consumer" \
                                    --container-name="search-issues-consumer" \
                                    --container-name="snuba-admin" \
                                    --container-name="transactions-consumer-new" \
                                    --container-name="transactions-subscriptions-executor" \
                                    --container-name="transactions-subscriptions-scheduler" \
                                    --container-name="rust-querylog-consumer" \
                                    --container-name="spans-consumer" \
                                    --container-name="dlq-consumer" \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=snuba" \
                                    --image="us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    --type="cronjob" \
                                    --container-name="cleanup" \
                                    --container-name="optimize"

            - migrate:
                  approval:
                      type: manual
                  fetch_materials: true
                  jobs:
                      migrate:
                          timeout: 1200
                          elastic_profile_id: snuba
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-spawn-job.py \
                                    --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                    --label-selector="service=snuba-admin" \
                                    --container-name="snuba-admin" \
                                    "snuba-migrate" "us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                    -- snuba migrations migrate -r complete -r partial
                              - plugin:
                                    options:
                                        script: |
                                            /devinfra/scripts/k8s/k8stunnel \
                                            && /devinfra/scripts/k8s/k8s-spawn-job.py \
                                            --context="gke_${GCP_PROJECT}_${GKE_REGION}-${GKE_CLUSTER_ZONE}_${GKE_CLUSTER}" \
                                            --label-selector="service=snuba-admin" \
                                            --container-name="snuba-admin" \
                                            "snuba-migrate-reverse" "us.gcr.io/sentryio/snuba:${GO_REVISION_SNUBA_REPO}" \
                                            -- snuba migrations reverse-in-progress
                                    run_if: failed
                                    configuration:
                                        id: script-executor
                                        version: 1
