format_version: 10
pipelines:
  deploy-snuba:
    display_order: 0
    group: snuba
    lock_behavior: unlockWhenFinished
    materials:
      snuba_repo:
        branch: master
        destination: snuba
        git: git@github.com:getsentry/snuba.git
        shallow_clone: true
    stages:
      - pipeline-complete:
          approval:
            type: manual
          jobs:
            pipeline-complete:
              tasks:
                - exec:
                    command: true
