"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RequestInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_IDS_FIELD_NUMBER: builtins.int
    ORGANIZATION_IDS_FIELD_NUMBER: builtins.int
    COGS_CATEGORY_FIELD_NUMBER: builtins.int
    REFERRER_FIELD_NUMBER: builtins.int
    START_TIMESTAMP_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_FIELD_NUMBER: builtins.int
    cogs_category: builtins.str
    referrer: builtins.str
    @property
    def project_ids(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.int
    ]: ...
    @property
    def organization_ids(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        builtins.int
    ]: ...
    @property
    def start_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        project_ids: collections.abc.Iterable[builtins.int] | None = ...,
        organization_ids: collections.abc.Iterable[builtins.int] | None = ...,
        cogs_category: builtins.str = ...,
        referrer: builtins.str = ...,
        start_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "end_timestamp", b"end_timestamp", "start_timestamp", b"start_timestamp"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "cogs_category",
            b"cogs_category",
            "end_timestamp",
            b"end_timestamp",
            "organization_ids",
            b"organization_ids",
            "project_ids",
            b"project_ids",
            "referrer",
            b"referrer",
            "start_timestamp",
            b"start_timestamp",
        ],
    ) -> None: ...

global___RequestInfo = RequestInfo

@typing.final
class PentityFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ATTRIBUTE_NAME_FIELD_NUMBER: builtins.int
    COMPARISON_FIELD_NUMBER: builtins.int
    STRING_LITERAL_FIELD_NUMBER: builtins.int
    INT_LITERAL_FIELD_NUMBER: builtins.int
    FLOAT_LITERAL_FIELD_NUMBER: builtins.int
    attribute_name: builtins.str
    comparison: builtins.str
    """should maybe make this an enum later"""
    string_literal: builtins.str
    int_literal: builtins.int
    float_literal: builtins.float
    def __init__(
        self,
        *,
        attribute_name: builtins.str = ...,
        comparison: builtins.str = ...,
        string_literal: builtins.str = ...,
        int_literal: builtins.int = ...,
        float_literal: builtins.float = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "float_literal",
            b"float_literal",
            "int_literal",
            b"int_literal",
            "string_literal",
            b"string_literal",
            "value",
            b"value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "attribute_name",
            b"attribute_name",
            "comparison",
            b"comparison",
            "float_literal",
            b"float_literal",
            "int_literal",
            b"int_literal",
            "string_literal",
            b"string_literal",
            "value",
            b"value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["value", b"value"]
    ) -> typing.Literal["string_literal", "int_literal", "float_literal"] | None: ...

global___PentityFilter = PentityFilter

@typing.final
class PentityFilters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PENTITY_NAME_FIELD_NUMBER: builtins.int
    FILTERS_FIELD_NUMBER: builtins.int
    pentity_name: builtins.str
    @property
    def filters(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___PentityFilter
    ]: ...
    def __init__(
        self,
        *,
        pentity_name: builtins.str = ...,
        filters: collections.abc.Iterable[global___PentityFilter] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "filters", b"filters", "pentity_name", b"pentity_name"
        ],
    ) -> None: ...

global___PentityFilters = PentityFilters

@typing.final
class PentityAggregation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGGREGATION_TYPE_FIELD_NUMBER: builtins.int
    PENTITY_NAME_FIELD_NUMBER: builtins.int
    ATTRIBUTE_NAME_FIELD_NUMBER: builtins.int
    aggregation_type: builtins.str
    pentity_name: builtins.str
    attribute_name: builtins.str
    def __init__(
        self,
        *,
        aggregation_type: builtins.str = ...,
        pentity_name: builtins.str = ...,
        attribute_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aggregation_type",
            b"aggregation_type",
            "attribute_name",
            b"attribute_name",
            "pentity_name",
            b"pentity_name",
        ],
    ) -> None: ...

global___PentityAggregation = PentityAggregation
