# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base_messages.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'base_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61se_messages.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n\x0bRequestInfo\x12\x13\n\x0bproject_ids\x18\x01 \x03(\x04\x12\x18\n\x10organization_ids\x18\x02 \x03(\x04\x12\x15\n\rcogs_category\x18\x03 \x01(\t\x12\x10\n\x08referrer\x18\x04 \x01(\t\x12\x33\n\x0fstart_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rend_timestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xc8\x01\n\rPentityFilter\x12\x16\n\x0e\x61ttribute_name\x18\x01 \x01(\t\x12\x1f\n\ncomparison\x18\x02 \x01(\x0e\x32\x0b.Comparison\x12\x18\n\x0estring_literal\x18\x03 \x01(\tH\x00\x12\x15\n\x0bint_literal\x18\x04 \x01(\x03H\x00\x12\x17\n\rfloat_literal\x18\x05 \x01(\x02H\x00\x12\x11\n\tint_array\x18\x06 \x03(\x03\x12\x11\n\tstr_array\x18\x07 \x03(\tB\x0e\n\x0cscalar_value\"G\n\x0ePentityFilters\x12\x14\n\x0cpentity_name\x18\x01 \x01(\t\x12\x1f\n\x07\x66ilters\x18\x02 \x03(\x0b\x32\x0e.PentityFilter\"n\n\x12PentityAggregation\x12*\n\x10\x61ggregation_type\x18\x01 \x01(\x0e\x32\x10.AggregationType\x12\x14\n\x0cpentity_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61ttribute_name\x18\x03 \x01(\t*k\n\nComparison\x12\x06\n\x02\x45Q\x10\x00\x12\x07\n\x03NEQ\x10\x01\x12\x06\n\x02LE\x10\x02\x12\x06\n\x02GT\x10\x03\x12\x07\n\x03LTE\x10\x04\x12\x07\n\x03GTE\x10\x05\x12\x08\n\x04LIKE\x10\x06\x12\x0c\n\x08NOT_LIKE\x10\x07\x12\x06\n\x02IN\x10\x08\x12\n\n\x06NOT_IN\x10\t*e\n\x0f\x41ggregationType\x12\x07\n\x03\x41VG\x10\x00\x12\x07\n\x03MIN\x10\x01\x12\x07\n\x03MAX\x10\x02\x12\x07\n\x03P50\x10\x04\x12\x07\n\x03P90\x10\x05\x12\x07\n\x03P95\x10\x06\x12\x07\n\x03P99\x10\x07\x12\t\n\x05\x43OUNT\x10\x08\x12\x08\n\x04UNIQ\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPARISON']._serialized_start=652
  _globals['_COMPARISON']._serialized_end=759
  _globals['_AGGREGATIONTYPE']._serialized_start=761
  _globals['_AGGREGATIONTYPE']._serialized_end=862
  _globals['_REQUESTINFO']._serialized_start=57
  _globals['_REQUESTINFO']._serialized_end=262
  _globals['_PENTITYFILTER']._serialized_start=265
  _globals['_PENTITYFILTER']._serialized_end=465
  _globals['_PENTITYFILTERS']._serialized_start=467
  _globals['_PENTITYFILTERS']._serialized_end=538
  _globals['_PENTITYAGGREGATION']._serialized_start=540
  _globals['_PENTITYAGGREGATION']._serialized_end=650
# @@protoc_insertion_point(module_scope)
