# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FindTrace.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 1, "", "FindTrace.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x46indTrace.proto"\xe7\x02\n\x10\x46indTraceRequest\x12)\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x18.FindTraceRequest.Filter\x1a)\n\x15SpanWithAttrKeyExists\x12\x10\n\x08\x61ttr_key\x18\x01 \x01(\t\x1a\x42\n\x1aSpanWithAttrKeyEqualsValue\x12\x10\n\x08\x61ttr_key\x18\x01 \x01(\t\x12\x12\n\nattr_value\x18\x02 \x01(\t\x1a\xb8\x01\n\x06\x46ilter\x12L\n\x19span_with_attr_key_exists\x18\x01 \x01(\x0b\x32\'.FindTraceRequest.SpanWithAttrKeyExistsH\x00\x12W\n\x1fspan_with_attr_key_equals_value\x18\x02 \x01(\x0b\x32,.FindTraceRequest.SpanWithAttrKeyEqualsValueH\x00\x42\x07\n\x05value"(\n\x11\x46indTraceResponse\x12\x13\n\x0btrace_uuids\x18\x01 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "FindTrace_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FINDTRACEREQUEST"]._serialized_start = 20
    _globals["_FINDTRACEREQUEST"]._serialized_end = 379
    _globals["_FINDTRACEREQUEST_SPANWITHATTRKEYEXISTS"]._serialized_start = 83
    _globals["_FINDTRACEREQUEST_SPANWITHATTRKEYEXISTS"]._serialized_end = 124
    _globals["_FINDTRACEREQUEST_SPANWITHATTRKEYEQUALSVALUE"]._serialized_start = 126
    _globals["_FINDTRACEREQUEST_SPANWITHATTRKEYEQUALSVALUE"]._serialized_end = 192
    _globals["_FINDTRACEREQUEST_FILTER"]._serialized_start = 195
    _globals["_FINDTRACEREQUEST_FILTER"]._serialized_end = 379
    _globals["_FINDTRACERESPONSE"]._serialized_start = 381
    _globals["_FINDTRACERESPONSE"]._serialized_end = 421
# @@protoc_insertion_point(module_scope)
