# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snuba/protobufs/FindTrace.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'snuba/protobufs/FindTrace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from snuba.protobufs import Filters_pb2 as snuba_dot_protobufs_dot_Filters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsnuba/protobufs/FindTrace.proto\x1a\x1dsnuba/protobufs/Filters.proto\"5\n\x10\x46indTraceRequest\x12!\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x10.TraceItemFilter\"(\n\x11\x46indTraceResponse\x12\x13\n\x0btrace_uuids\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snuba.protobufs.FindTrace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINDTRACEREQUEST']._serialized_start=66
  _globals['_FINDTRACEREQUEST']._serialized_end=119
  _globals['_FINDTRACERESPONSE']._serialized_start=121
  _globals['_FINDTRACERESPONSE']._serialized_end=161
# @@protoc_insertion_point(module_scope)
