"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import base_messages_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_INFO_FIELD_NUMBER: builtins.int
    PENTITY_FILTERS_FIELD_NUMBER: builtins.int
    PENTITY_AGGREGATION_FIELD_NUMBER: builtins.int
    @property
    def request_info(self) -> base_messages_pb2.RequestInfo: ...
    @property
    def pentity_filters(self) -> base_messages_pb2.PentityFilters: ...
    @property
    def pentity_aggregation(self) -> base_messages_pb2.PentityAggregation: ...
    def __init__(
        self,
        *,
        request_info: base_messages_pb2.RequestInfo | None = ...,
        pentity_filters: base_messages_pb2.PentityFilters | None = ...,
        pentity_aggregation: base_messages_pb2.PentityAggregation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "pentity_aggregation",
            b"pentity_aggregation",
            "pentity_filters",
            b"pentity_filters",
            "request_info",
            b"request_info",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "pentity_aggregation",
            b"pentity_aggregation",
            "pentity_filters",
            b"pentity_filters",
            "request_info",
            b"request_info",
        ],
    ) -> None: ...

global___TimeSeriesRequest = TimeSeriesRequest
