import { createStyles } from "@mantine/core";

export const useShellStyles = createStyles((theme) => ({
  shellContainer: {
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: "linear-gradient(180deg, #0d1117 0%, #161b22 100%)",
    borderRadius: theme.radius.md,
    fontFamily:
      '"JetBrains Mono", "Fira Code", "Source Code Pro", Consolas, monospace',
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.4)",
    border: "1px solid #30363d",
  },
  shellContainerSudo: {
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: "linear-gradient(180deg, #1a0a0a 0%, #2d1515 100%)",
    borderRadius: theme.radius.md,
    fontFamily:
      '"JetBrains Mono", "Fira Code", "Source Code Pro", Consolas, monospace',
    overflow: "hidden",
    boxShadow: "0 4px 24px rgba(255, 0, 0, 0.2)",
    border: "2px solid #f85149",
  },
  outputArea: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 16px",
    fontSize: "13px",
    lineHeight: 1.6,
    color: "#e6edf3",
    "&::-webkit-scrollbar": {
      width: "8px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#30363d",
      borderRadius: "4px",
    },
    "&::-webkit-scrollbar-thumb:hover": {
      background: "#484f58",
    },
  },
  suggestionsBar: {
    borderTop: "1px solid #30363d",
    padding: "6px 16px",
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    backgroundColor: "rgba(22, 27, 34, 0.95)",
    fontSize: "12px",
  },
  suggestionItem: {
    color: "#58a6ff",
    backgroundColor: "rgba(88, 166, 255, 0.1)",
    padding: "2px 8px",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.15s ease",
    "&:hover": {
      backgroundColor: "rgba(88, 166, 255, 0.2)",
      color: "#79c0ff",
    },
  },
  inputArea: {
    borderTop: "1px solid #30363d",
    padding: "8px 16px",
    display: "flex",
    alignItems: "flex-start",
    backgroundColor: "rgba(22, 27, 34, 0.8)",
  },
  prompt: {
    color: "#58a6ff",
    marginRight: "12px",
    fontSize: "14px",
    fontWeight: 700,
    textShadow: "0 0 10px rgba(88, 166, 255, 0.3)",
    lineHeight: "21px",
    paddingTop: "1px",
  },
  input: {
    flex: 1,
    backgroundColor: "transparent",
    border: "none",
    color: "#e6edf3",
    fontFamily: "inherit",
    fontSize: "14px",
    outline: "none",
    caretColor: "#58a6ff",
    resize: "none",
    lineHeight: "21px",
    minHeight: "21px",
    maxHeight: "210px",
    overflow: "auto",
    "&::placeholder": {
      color: "#6e7681",
    },
    "&::-webkit-scrollbar": {
      width: "6px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#30363d",
      borderRadius: "3px",
    },
  },
  statusBar: {
    borderTop: "1px solid #30363d",
    padding: "6px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "11px",
    color: "#8b949e",
    backgroundColor: "#010409",
    letterSpacing: "0.3px",
  },
  statusItem: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  statusActive: {
    color: "#3fb950",
    fontWeight: 600,
  },
  statusInactive: {
    color: "#6e7681",
  },
  statusWarn: {
    color: "#f85149",
    fontWeight: 700,
    textShadow: "0 0 8px rgba(248, 81, 73, 0.4)",
  },
  commandLine: {
    marginBottom: "12px",
    display: "flex",
    alignItems: "flex-start",
  },
  promptDisplay: {
    color: "#58a6ff",
    marginRight: "12px",
    fontWeight: 700,
    userSelect: "none",
  },
  commandText: {
    color: "#e6edf3",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  infoText: {
    color: "#58a6ff",
    padding: "4px 0",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  errorText: {
    color: "#f85149",
    padding: "8px 12px",
    backgroundColor: "rgba(248, 81, 73, 0.1)",
    borderRadius: "6px",
    borderLeft: "3px solid #f85149",
    marginBottom: "8px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  resultBox: {
    backgroundColor: "rgba(13, 17, 23, 0.6)",
    borderRadius: "8px",
    padding: "16px",
    marginTop: "12px",
    marginBottom: "12px",
    border: "1px solid #30363d",
  },
  resultHeader: {
    color: "#8b949e",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "12px",
    paddingBottom: "8px",
    borderBottom: "1px solid #21262d",
  },
  traceBox: {
    backgroundColor: "rgba(13, 17, 23, 0.6)",
    borderRadius: "8px",
    padding: "16px",
    marginTop: "12px",
    marginBottom: "12px",
    border: "1px solid #30363d",
    maxHeight: "300px",
    overflowY: "auto",
  },
  storageList: {
    color: "#e6edf3",
    listStyleType: "none",
    padding: "8px 0",
    margin: 0,
  },
  storageItem: {
    padding: "4px 12px",
    borderRadius: "4px",
    marginBottom: "2px",
    transition: "background-color 0.15s ease",
    "&:hover": {
      backgroundColor: "rgba(88, 166, 255, 0.1)",
    },
    "&:before": {
      content: '"→"',
      color: "#3fb950",
      marginRight: "8px",
    },
  },
  helpCommand: {
    color: "#ffa657",
    minWidth: "220px",
    display: "inline-block",
    fontWeight: 500,
  },
  helpDescription: {
    color: "#8b949e",
  },
  tableContainer: {
    overflowX: "auto",
    marginTop: "8px",
    borderRadius: "6px",
    border: "1px solid #30363d",
  },
  resultTable: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "12px",
    "& th": {
      backgroundColor: "#161b22",
      color: "#58a6ff",
      padding: "10px 14px",
      textAlign: "left",
      borderBottom: "1px solid #30363d",
      fontWeight: 600,
      fontSize: "11px",
      textTransform: "uppercase",
      letterSpacing: "0.3px",
    },
    "& td": {
      padding: "8px 14px",
      borderBottom: "1px solid #21262d",
      color: "#e6edf3",
    },
    "& tr:hover td": {
      backgroundColor: "rgba(88, 166, 255, 0.05)",
    },
    "& tr:last-child td": {
      borderBottom: "none",
    },
  },
  nodeHeader: {
    color: "#58a6ff",
    fontWeight: 600,
    marginTop: "12px",
    marginBottom: "6px",
    fontSize: "13px",
  },
  summaryText: {
    color: "#8b949e",
    marginLeft: "16px",
    fontSize: "12px",
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  executingIndicator: {
    color: "#ffa657",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 0",
    "&:before": {
      content: '""',
      width: "8px",
      height: "8px",
      backgroundColor: "#ffa657",
      borderRadius: "50%",
      animation: "pulse 1s ease-in-out infinite",
    },
    "@keyframes pulse": {
      "0%, 100%": { opacity: 1 },
      "50%": { opacity: 0.4 },
    },
  },
  // Collapsible section styles
  resultContainer: {
    marginTop: "8px",
    marginBottom: "8px",
  },
  collapsibleSection: {
    backgroundColor: "rgba(13, 17, 23, 0.6)",
    borderRadius: "6px",
    border: "1px solid #30363d",
    marginBottom: "6px",
    overflow: "hidden",
  },
  collapsibleHeader: {
    display: "flex",
    alignItems: "center",
    padding: "6px 10px",
    cursor: "pointer",
    userSelect: "none",
    backgroundColor: "rgba(22, 27, 34, 0.8)",
    "&:hover": {
      backgroundColor: "rgba(48, 54, 61, 0.6)",
    },
  },
  collapsibleChevron: {
    color: "#8b949e",
    fontSize: "10px",
    marginRight: "8px",
    width: "12px",
  },
  collapsibleTitle: {
    color: "#e6edf3",
    fontSize: "12px",
    fontWeight: 500,
  },
  collapsibleBadge: {
    marginLeft: "8px",
    padding: "1px 6px",
    backgroundColor: "rgba(88, 166, 255, 0.15)",
    color: "#58a6ff",
    borderRadius: "10px",
    fontSize: "10px",
    fontWeight: 500,
  },
  collapsibleContent: {
    padding: "8px 10px",
    borderTop: "1px solid #21262d",
  },
  // Compact result table styles
  resultTableCompact: {
    borderCollapse: "collapse",
    width: "100%",
    fontSize: "11px",
    "& th": {
      backgroundColor: "#161b22",
      color: "#58a6ff",
      padding: "6px 10px",
      textAlign: "left",
      borderBottom: "1px solid #30363d",
      fontWeight: 600,
      fontSize: "10px",
      textTransform: "uppercase",
      letterSpacing: "0.3px",
      whiteSpace: "nowrap",
      "& small": {
        color: "#6e7681",
        fontWeight: 400,
      },
    },
    "& td": {
      padding: "4px 10px",
      borderBottom: "1px solid #21262d",
      color: "#e6edf3",
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
      overflowWrap: "break-word",
    },
    "& tr:hover td": {
      backgroundColor: "rgba(88, 166, 255, 0.05)",
    },
    "& tr:last-child td": {
      borderBottom: "none",
    },
  },
  nullValue: {
    color: "#6e7681",
    fontStyle: "italic",
  },
  emptyResult: {
    color: "#6e7681",
    fontSize: "11px",
    fontStyle: "italic",
  },
  rawTraceContent: {
    maxHeight: "200px",
    overflowY: "auto",
    "&::-webkit-scrollbar": {
      width: "6px",
    },
    "&::-webkit-scrollbar-track": {
      background: "transparent",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#30363d",
      borderRadius: "3px",
    },
  },
  rawTraceLine: {
    color: "#e6edf3",
    fontSize: "11px",
    lineHeight: 1.4,
    fontFamily: "inherit",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  // JSON output format styles
  jsonOutput: {
    color: "#e6edf3",
    fontSize: "11px",
    lineHeight: 1.5,
    fontFamily: "inherit",
    margin: 0,
    padding: "8px",
    backgroundColor: "rgba(13, 17, 23, 0.4)",
    borderRadius: "4px",
    overflow: "auto",
    maxHeight: "400px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  // CSV output format styles
  csvOutput: {
    color: "#e6edf3",
    fontSize: "11px",
    lineHeight: 1.5,
    fontFamily: "inherit",
    margin: 0,
    padding: "8px",
    backgroundColor: "rgba(13, 17, 23, 0.4)",
    borderRadius: "4px",
    overflow: "auto",
    maxHeight: "400px",
    whiteSpace: "pre",
  },
  // Vertical output format styles
  verticalOutput: {
    fontSize: "11px",
    lineHeight: 1.5,
    fontFamily: "inherit",
  },
  verticalRow: {
    marginBottom: "12px",
  },
  verticalRowHeader: {
    color: "#ffa657",
    marginBottom: "4px",
    fontWeight: 500,
  },
  verticalField: {
    display: "flex",
    color: "#e6edf3",
    lineHeight: 1.6,
  },
  verticalFieldName: {
    color: "#58a6ff",
    whiteSpace: "pre",
    minWidth: "120px",
  },
  verticalFieldValue: {
    color: "#e6edf3",
    wordBreak: "break-word",
  },
}));
