# Ignored by docker compose, used by devservices
x-sentry-service-config:
  version: 0.1
  service_name: snuba
  dependencies:
    clickhouse:
      description: "Real time analytics database"
    redis:
      description: "Shared instance of redis used by sentry services"
      remote:
        repo_name: sentry-shared-redis
        branch: main
        repo_link: git@github.com:getsentry/sentry-shared-redis.git
    kafka:
      description: "Shared instance of kafka used by sentry services"
      remote:
        repo_name: sentry-shared-kafka
        branch: main
        repo_link: git@github.com:getsentry/sentry-shared-kafka.git
    snuba:
      description: "Service that provides a rich data model on top of Clickhouse together with a fast ingestion consumer and a query optimizer"
  modes:
    default: [redis, kafka, clickhouse]
    containerized: [clickhouse, redis, kafka, snuba]

services:
  clickhouse:
    image: "ghcr.io/getsentry/image-mirror-altinity-clickhouse-server:23.8.11.29.altinitystable"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8123:8123"
    volumes:
      - "clickhouse:/var/lib/clickhouse"
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.d/sentry.xml"
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - sentry
  snuba:
    image: ghcr.io/getsentry/snuba:latest
    ports:
      - '1218:1218'
      - '1219:1219'
    command: ['devserver']
    environment:
      PYTHONUNBUFFERED: '1'
      SNUBA_SETTINGS: docker
      DEBUG: '1'
      CLICKHOUSE_HOST: 'clickhouse'
      CLICKHOUSE_PORT: '9000'
      CLICKHOUSE_HTTP_PORT: '8123'
      DEFAULT_BROKERS: 'kafka:9093'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_DB: '1'
      ENABLE_SENTRY_METRICS_DEV: '${ENABLE_SENTRY_METRICS_DEV:-}'
      ENABLE_PROFILES_CONSUMER: '${ENABLE_PROFILES_CONSUMER:-}'
      ENABLE_SPANS_CONSUMER: '${ENABLE_SPANS_CONSUMER:-}'
      ENABLE_ISSUE_OCCURRENCE_CONSUMER: '${ENABLE_ISSUE_OCCURRENCE_CONSUMER:-}'
      ENABLE_AUTORUN_MIGRATION_SEARCH_ISSUES: '1'
      ENABLE_GROUP_ATTRIBUTES_CONSUMER: '${ENABLE_GROUP_ATTRIBUTES_CONSUMER:-}'
    platform: linux/amd64
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - sentry

volumes:
  clickhouse:

networks:
  sentry:
    name: sentry
