const COLORS = {
  HEADER_BG: "#303030",
  HEADER_TEXT: "white",
  NAV_ACTIVE_TEXT: "black",
  NAV_INACTIVE_TEXT: "#858585",
  NAV_BORDER: "#CBCBCB",
  TABLE_BORDER: "#CBCBCB",
  SNUBA_BLUE: "#4681e0",
};

export { COLORS };
