version: v1
kind: writable_storage
name: profiles
storage:
  key: profiles
  set_key: profiles
readiness_state: complete
schema:
  columns:
    [
      { name: organization_id, type: UInt, args: { size: 64 } },
      { name: project_id, type: UInt, args: { size: 64 } },
      { name: transaction_id, type: UUID },
      { name: profile_id, type: UUID },
      { name: received, type: DateTime },
      {
        name: android_api_level,
        type: UInt,
        args: { schema_modifiers: [nullable], size: 32 },
      },
      { name: device_classification, type: String },
      { name: device_locale, type: String },
      { name: device_manufacturer, type: String },
      { name: device_model, type: String },
      {
        name: device_os_build_number,
        type: String,
        args: { schema_modifiers: [nullable] },
      },
      { name: device_os_name, type: String },
      { name: device_os_version, type: String },
      { name: architecture, type: String },
      { name: duration_ns, type: UInt, args: { size: 64 } },
      {
        name: environment,
        type: String,
        args: { schema_modifiers: [nullable] },
      },
      { name: platform, type: String },
      { name: trace_id, type: UUID },
      { name: transaction_name, type: String },
      { name: version_name, type: String },
      { name: version_code, type: String },
      { name: retention_days, type: UInt, args: { size: 16 } },
      { name: partition, type: UInt, args: { size: 16 } },
      { name: offset, type: UInt, args: { size: 64 } },
    ]
  local_table_name: profiles_local
  dist_table_name: profiles_dist
query_processors:
  - processor: UUIDColumnProcessor
    args:
      columns: !!set
        trace_id: null
        transaction_id: null
        profile_id: null
  - processor: TableRateLimit
allocation_policies:
  - name: ConcurrentRateLimitAllocationPolicy
    args:
      required_tenant_types:
        - organization_id
        - referrer
        - project_id
      default_config_overrides:
        is_enforced: 0
  - name: BytesScannedWindowAllocationPolicy
    args:
      required_tenant_types:
        - organization_id
        - referrer
      default_config_overrides:
        is_enforced: 1
        throttled_thread_number: 1
        org_limit_bytes_scanned: 100000
mandatory_condition_checkers:
  - condition: OrgIdEnforcer
    args:
      field_name: organization_id
  - condition: ProjectIdEnforcer
stream_loader:
  processor:
    name: ProfilesMessageProcessor
  default_topic: processed-profiles
