from typing import Sequence

from snuba.clusters.storage_sets import StorageSetKey
from snuba.migrations.columns import MigrationModifiers
from snuba.migrations.migration import ClickhouseNodeMigration
from snuba.migrations.operations import (
    AddColumn,
    DropColumn,
    OperationTarget,
    SqlOperation,
)
from snuba.utils import schemas
from snuba.utils.schemas import Column


class Migration(ClickhouseNodeMigration):
    blocking = False

    def forwards_ops(self) -> Sequence[SqlOperation]:
        return [
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column=Column(
                    "geo_city",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="count_info_events",
                target=OperationTarget.LOCAL,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column=Column(
                    "geo_city",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="count_info_events",
                target=OperationTarget.DISTRIBUTED,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column=Column(
                    "geo_country_code",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_city",
                target=OperationTarget.LOCAL,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column=Column(
                    "geo_country_code",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_city",
                target=OperationTarget.DISTRIBUTED,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column=Column(
                    "geo_region",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_country_code",
                target=OperationTarget.LOCAL,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column=Column(
                    "geo_region",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_country_code",
                target=OperationTarget.DISTRIBUTED,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column=Column(
                    "geo_subdivision",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_region",
                target=OperationTarget.LOCAL,
            ),
            AddColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column=Column(
                    "geo_subdivision",
                    schemas.String(
                        modifiers=MigrationModifiers(
                            nullable=True,
                            low_cardinality=False,
                            default=None,
                            materialized=None,
                            codecs=None,
                            ttl=None,
                        )
                    ),
                ),
                after="geo_region",
                target=OperationTarget.DISTRIBUTED,
            ),
        ]

    def backwards_ops(self) -> Sequence[SqlOperation]:
        return [
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column_name="geo_subdivision",
                target=OperationTarget.DISTRIBUTED,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column_name="geo_subdivision",
                target=OperationTarget.LOCAL,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column_name="geo_region",
                target=OperationTarget.DISTRIBUTED,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column_name="geo_region",
                target=OperationTarget.LOCAL,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column_name="geo_country_code",
                target=OperationTarget.DISTRIBUTED,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column_name="geo_country_code",
                target=OperationTarget.LOCAL,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_dist",
                column_name="geo_city",
                target=OperationTarget.DISTRIBUTED,
            ),
            DropColumn(
                storage_set=StorageSetKey.REPLAYS,
                table_name="replays_local",
                column_name="geo_city",
                target=OperationTarget.LOCAL,
            ),
        ]
