import json
from datetime import UTC, date, datetime
from typing import Any, cast
from unittest import mock

import pytest

from snuba.clickhouse.connect import ClickhouseConnectPool, _insert_statement
from snuba.clickhouse.errors import ClickhouseError
from snuba.clickhouse.formatter.nodes import FormattedQuery
from snuba.clusters.cluster import ClickhouseClientSettings

# Error code returned by ClickHouse when the maximum number of simultaneous
# queries has been exceeded.
TOO_MANY_SIMULTANEOUS_QUERIES = 202


@pytest.fixture(autouse=True)
def _clear_shared_pools() -> Any:
    # _new_client caches get_pool_manager() in a process-wide dict. Tests that
    # patch it would otherwise leak a MagicMock into later clickhouse_db tests.
    import snuba.clickhouse.connect as connect_mod

    yield
    connect_mod._pool_managers.clear()


class FakeColumnType:
    def __init__(self, name: str) -> None:
        self.name = name


class FakeQueryResult:
    def __init__(
        self,
        result_set: Any,
        column_names: Any = (),
        column_types: Any = (),
        summary: Any = None,
        query_id: str = "",
    ) -> None:
        self.result_set = result_set
        self.column_names = column_names
        self.column_types = column_types
        self.summary = summary or {}
        self._query_id = query_id

    @property
    def query_id(self) -> str:
        # Mirror clickhouse_connect.driver.query.QueryResult.query_id.
        summary_id = self.summary.get("query_id")
        if summary_id:
            return str(summary_id)
        return self._query_id or ""

    def close(self) -> None:
        return None


def _make_pool(client: mock.Mock, **kwargs: Any) -> ClickhouseConnectPool:
    client.server_tz = UTC
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="test",
        **kwargs,
    )
    pool._new_client = lambda **_: client  # type: ignore[method-assign]
    return pool


def test_execute_maps_result_and_profile() -> None:
    # Typed SELECTs use a single JSONCompact request so empty and non-empty
    # results both return real meta without a second scan.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "id", "type": "UInt64"},
                {"name": "name", "type": "String"},
            ],
            "data": [[1, "a"], [2, "b"]],
            "statistics": {
                "rows_read": 2,
                "bytes_read": 128,
                "elapsed": 1.5,
            },
            "query_id": "server-assigned-id",
        }
    ).encode()

    pool = _make_pool(client)
    result = pool.execute("SELECT id, name FROM t", with_column_types=True)

    assert result.results == [(1, "a"), (2, "b")]
    assert result.meta == [("id", "UInt64"), ("name", "String")]
    assert result.profile is not None
    assert result.profile["rows"] == 2
    assert result.profile["bytes"] == 128
    assert result.profile["elapsed"] == 1.5
    assert result.query_id == "server-assigned-id"
    client.query.assert_not_called()
    assert client.raw_query.call_args.kwargs["fmt"] == "JSONCompact"


def test_execute_passes_datetime_meta_through() -> None:
    # Do not rewrite ClickHouse DateTime meta to DateTime('Universal').
    # Sentry already treats DateTime and DateTime(...) as dates.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "time", "type": "DateTime"}],
            "data": [["2023-01-02 03:04:05"]],
        }
    ).encode()
    client.server_tz = None

    result = _make_pool(client).execute("SELECT now()", with_column_types=True)

    assert result.meta == [("time", "DateTime")]
    assert result.results == [(datetime(2023, 1, 2, 3, 4, 5),)]


def test_execute_surfaces_client_autogenerated_query_id() -> None:
    client = mock.Mock()
    # No payload query_id; fall back to the caller-supplied / empty id.
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "x", "type": "UInt8"}],
            "data": [[1]],
            "query_id": "client-generated-id",
        }
    ).encode()

    pool = _make_pool(client)
    result = pool.execute("SELECT 1", with_column_types=True)

    assert result.query_id == "client-generated-id"


def test_execute_passes_query_id_and_settings() -> None:
    client = mock.Mock()
    client.query.return_value = FakeQueryResult(result_set=[])

    pool = _make_pool(client)
    pool.execute(
        "SELECT 1",
        query_id="my-query-id",
        settings={"max_threads": 4},
    )

    args, kwargs = client.query.call_args
    assert args[0] == "SELECT 1"
    assert kwargs["settings"]["query_id"] == "my-query-id"
    assert kwargs["settings"]["max_threads"] == 4
    assert kwargs["transport_settings"] == {"X-ClickHouse-Format": "Native"}


@pytest.mark.parametrize(
    "query",
    [
        "CREATE DATABASE snuba_test",
        "  DROP DATABASE IF EXISTS snuba_test",
    ],
)
def test_database_ddl_does_not_require_current_database(query: str) -> None:
    client = mock.Mock()
    client.query.return_value = FakeQueryResult(result_set=[])
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="snuba_test",
    )

    with mock.patch.object(pool, "_new_client", return_value=client) as new_client:
        pool.execute(query)

    new_client.assert_called_once_with(use_database=False, query_limit=None)


def test_regular_query_uses_current_database() -> None:
    client = mock.Mock()
    client.query.return_value = FakeQueryResult(result_set=[[1]])
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="snuba_test",
    )

    with mock.patch.object(pool, "_new_client", return_value=client) as new_client:
        pool.execute("SELECT 1")

    new_client.assert_called_once_with(use_database=True, query_limit=None)


def test_execute_sets_native_format_for_embedded_insert_sql() -> None:
    client = mock.Mock()
    client.query.return_value = FakeQueryResult(result_set=[])

    sql = (
        "SELECT trace_id FROM eap_items_1_dist_ro WHERE equals(transaction, "
        "'db.query: \n      INSERT INTO sse_event_log (channel_id, event_id) "
        "VALUES (?, ?) ON CONFLICT DO NOTHING')"
    )
    pool = _make_pool(client)
    pool.execute(sql, query_id="qid")

    args, kwargs = client.query.call_args
    assert args[0] == sql
    assert kwargs["settings"]["query_id"] == "qid"
    assert kwargs["transport_settings"] == {"X-ClickHouse-Format": "Native"}


def test_insert_dict_rows_use_client_insert() -> None:
    client = mock.Mock()

    pool = _make_pool(client)
    ts = datetime(2026, 7, 8, 21, 14, 31)
    rows = [
        {
            "group": "events",
            "migration_id": "0025_add_segment_names_column",
            "timestamp": ts,
            "status": "in_progress",
            "version": 3,
        }
    ]

    pool.insert("migrations_local", rows)

    client.query.assert_not_called()
    args, kwargs = client.insert.call_args
    assert args[0] == "migrations_local"
    assert kwargs["database"] == "test"
    assert kwargs["column_names"] == [
        "group",
        "migration_id",
        "timestamp",
        "status",
        "version",
    ]
    assert args[1] == [["events", "0025_add_segment_names_column", ts, "in_progress", 3]]


def test_insert_multiple_rows_build_a_matrix() -> None:
    client = mock.Mock()

    pool = _make_pool(client)
    rows = [
        {"g": 1, "ts": datetime(2023, 1, 2, 3, 4, 5), "v": 10},
        {"g": 2, "ts": datetime(2023, 1, 3, 0, 0, 0), "v": 30},
    ]

    pool.insert("metrics", rows)

    _, kwargs = client.insert.call_args
    assert kwargs["database"] == "test"
    assert kwargs["column_names"] == ["g", "ts", "v"]
    assert client.insert.call_args[0][1] == [
        [1, datetime(2023, 1, 2, 3, 4, 5), 10],
        [2, datetime(2023, 1, 3, 0, 0, 0), 30],
    ]


def test_insert_statement_mirrors_what_the_driver_sends() -> None:
    assert (
        _insert_statement("migrations_local", ["group", "migration_id"])
        == "INSERT INTO migrations_local (`group`, `migration_id`) FORMAT Native"
    )


def test_insert_empty_rows_short_circuits() -> None:
    client = mock.Mock()

    pool = _make_pool(client)
    pool.insert("t", [])

    client.insert.assert_not_called()
    client.query.assert_not_called()


def test_insert_forwards_query_id_and_settings() -> None:
    client = mock.Mock()

    pool = _make_pool(client)
    pool.insert(
        "t",
        [{"a": 1}],
        query_id="insert-id",
        settings={"async_insert": 1},
    )

    _, kwargs = client.insert.call_args
    assert kwargs["database"] == "test"
    assert kwargs["settings"]["query_id"] == "insert-id"
    assert kwargs["settings"]["async_insert"] == 1


def test_execute_does_not_handle_insert_rows() -> None:
    client = mock.Mock()
    client.query.return_value = FakeQueryResult(result_set=[[1]])

    pool = _make_pool(client)
    pool.execute("SELECT %(x)s", {"x": 1})

    client.insert.assert_not_called()
    client.query.assert_called_once()


def test_too_many_simultaneous_queries_not_retried() -> None:
    # Plain execute retries transport failures only. Server errors like
    # TOO_MANY_SIMULTANEOUS_QUERIES still surface immediately.
    from clickhouse_connect.driver.exceptions import DatabaseError

    client = mock.Mock()
    client.query.side_effect = DatabaseError("too many", code=TOO_MANY_SIMULTANEOUS_QUERIES)

    pool = _make_pool(client)
    try:
        pool.execute("SELECT 1")
        raise AssertionError("expected a ClickhouseError to be raised")
    except ClickhouseError as error:
        assert error.code == TOO_MANY_SIMULTANEOUS_QUERIES
    # No retry on the plain execute path for server errors.
    assert client.query.call_count == 1


def test_shared_pool_uses_urllib3_retry() -> None:
    from snuba.clickhouse.connect import _TRANSPORT_RETRY, _close_pools, _shared_pool

    with mock.patch("snuba.clickhouse.connect.get_pool_manager") as get_pool_manager:
        get_pool_manager.return_value = mock.Mock()
        _close_pools()
        _shared_pool(None, False)
        assert get_pool_manager.call_args.kwargs["retries"] is _TRANSPORT_RETRY
        assert _TRANSPORT_RETRY.total == 2
        assert _TRANSPORT_RETRY.connect == 2
        assert _TRANSPORT_RETRY.read == 2


def test_execute_robust_retries_too_many_simultaneous_queries() -> None:
    # execute_robust must keep the old native-pool tenacity for concurrent load.
    from clickhouse_connect.driver.exceptions import DatabaseError

    client = mock.Mock()
    client.query.side_effect = [
        DatabaseError("too many", code=TOO_MANY_SIMULTANEOUS_QUERIES),
        DatabaseError("too many", code=TOO_MANY_SIMULTANEOUS_QUERIES),
        FakeQueryResult(result_set=[[1]]),
    ]

    pool = _make_pool(client)
    with mock.patch("snuba.clickhouse.connect.time.sleep") as sleep:
        result = pool.execute_robust("SELECT 1")

    assert result.results == [[1]]
    assert client.query.call_count == 3
    assert sleep.call_count == 2


def test_execute_robust_gives_up_after_too_many_simultaneous_retries() -> None:
    from clickhouse_connect.driver.exceptions import DatabaseError

    client = mock.Mock()
    client.query.side_effect = DatabaseError("too many", code=TOO_MANY_SIMULTANEOUS_QUERIES)

    pool = _make_pool(client)
    with (
        mock.patch("snuba.clickhouse.connect.time.sleep"),
        pytest.raises(ClickhouseError) as excinfo,
    ):
        pool.execute_robust("SELECT 1")

    assert excinfo.value.code == TOO_MANY_SIMULTANEOUS_QUERIES
    assert client.query.call_count == 3


def test_generic_clickhouse_error_wrapped() -> None:
    from clickhouse_connect.driver.exceptions import ProgrammingError

    client = mock.Mock()
    client.query.side_effect = ProgrammingError("bad query")

    pool = _make_pool(client)
    with pytest.raises(ClickhouseError) as excinfo:
        pool.execute("SELECT 1")

    assert excinfo.value.code == 0
    assert client.query.call_count == 1


def test_totals_malformed_json_wrapped() -> None:
    # A non-JSON totals response (truncation, a proxy error page) surfaces as a
    # ClickhouseError rather than leaking a raw JSONDecodeError.
    client = mock.Mock()
    client.raw_query.return_value = b"<html>502 Bad Gateway</html>"

    pool = _make_pool(client)
    with pytest.raises(ClickhouseError):
        pool.execute_with_totals("SELECT g, sum(v) FROM t GROUP BY g WITH TOTALS")


def test_command_does_not_query() -> None:
    client = mock.Mock()
    pool = _make_pool(client)

    result = pool.command("SYSTEM START MERGES")

    client.command.assert_called_once()
    client.query.assert_not_called()
    assert result.results == []
    assert result.meta == []


def test_new_client_defers_database_until_after_connect() -> None:
    import clickhouse_connect

    # clickhouse-connect attaches the client database to its autoconnect
    # probes. Passing it into get_client fails hard when the DB is missing
    # (test bootstrap, migrations). Mirror the native driver: connect first,
    # then set the default database for subsequent queries.
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="snuba_test",
    )
    fake_client = mock.Mock()

    with (
        mock.patch.object(clickhouse_connect, "get_client", return_value=fake_client) as get_client,
        mock.patch("snuba.clickhouse.connect.get_pool_manager"),
    ):
        client = pool._new_client()

    assert client is fake_client
    _, kwargs = get_client.call_args
    assert "database" not in kwargs
    assert fake_client.database == "snuba_test"


def test_timeouts_are_passed_through() -> None:
    import clickhouse_connect

    # The per-profile timeout is honored as-is (no capping), the same way the
    # native driver uses it. A large timeout (e.g. from MIGRATE) is preserved.
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="test",
        connect_timeout=60,
        send_receive_timeout=300000,
    )

    with (
        mock.patch.object(clickhouse_connect, "get_client") as get_client,
        mock.patch("snuba.clickhouse.connect.get_pool_manager"),
    ):
        pool._new_client()

    _, kwargs = get_client.call_args
    assert kwargs["send_receive_timeout"] == 300000
    assert kwargs["connect_timeout"] == 60
    assert kwargs["compress"] == "lz4"
    # Query-level retries stay off; urllib3 Retry on the pool handles blips.
    assert kwargs["query_retries"] == 0


def test_send_receive_timeout_defaults_when_profile_has_none() -> None:
    import clickhouse_connect

    from snuba.clickhouse.connect import DEFAULT_SEND_RECEIVE_TIMEOUT_SECONDS

    # A profile with no timeout (None) means "unbounded"; over
    # HTTP that maps to a large finite timeout, since clickhouse-connect can't
    # take None.
    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="test",
        send_receive_timeout=None,
    )

    with (
        mock.patch.object(clickhouse_connect, "get_client") as get_client,
        mock.patch("snuba.clickhouse.connect.get_pool_manager"),
    ):
        pool._new_client()

    _, kwargs = get_client.call_args
    assert kwargs["send_receive_timeout"] == DEFAULT_SEND_RECEIVE_TIMEOUT_SECONDS


def test_timeout_options_override_constructor_values() -> None:
    import clickhouse_connect
    from sentry_options.testing import override_options

    pool = ClickhouseConnectPool(
        host="host",
        user="test",
        password="test",
        database="test",
        connect_timeout=1,
        send_receive_timeout=25,
    )

    with (
        override_options(
            "snuba",
            {
                "clickhouse_connect_connect_timeout": 7,
                "clickhouse_connect_send_receive_timeout": 99,
            },
        ),
        mock.patch.object(clickhouse_connect, "get_client") as get_client,
        mock.patch("snuba.clickhouse.connect.get_pool_manager"),
    ):
        pool._new_client()

    _, kwargs = get_client.call_args
    assert kwargs["connect_timeout"] == 7
    assert kwargs["send_receive_timeout"] == 99


def test_read_query_client_settings_use_25s_timeout() -> None:
    # Read queries (the QUERY profile) get a 25s timeout on both drivers, leaving
    # headroom under the frontend request budget.

    settings = ClickhouseClientSettings.QUERY.value
    assert settings.settings == {}
    assert settings.timeout == 25


def test_tracing_client_settings_use_25s_timeout() -> None:
    # Tracing queries (the TRACING profile) get a 25s timeout on both drivers, leaving
    # headroom under the frontend request budget.

    settings = ClickhouseClientSettings.TRACING.value
    assert settings.settings == {"readonly": 2, "max_execution_time": 25}
    assert settings.timeout == 25


def test_internal_profile_has_no_explicit_timeout() -> None:
    # INTERNAL leaves timeout unset; the connect driver applies
    # DEFAULT_SEND_RECEIVE_TIMEOUT_SECONDS when building the client.
    assert ClickhouseClientSettings.INTERNAL.value.timeout is None


def test_clickhouse_reader_wraps_connect_pool() -> None:
    # The single driver-agnostic ClickhouseReader wraps the abstract pool, so it
    # works with the connect pool.
    from snuba.clickhouse.pool import ClickhouseReader

    pool = _make_pool(mock.Mock())
    reader = ClickhouseReader(cache_partition_id=None, client=pool, query_settings_prefix=None)
    assert isinstance(reader, ClickhouseReader)


def test_with_totals_via_single_jsoncompact_request() -> None:
    # WITH TOTALS runs through a single FORMAT JSONCompact request (data + meta +
    # totals), appending the totals as the trailing row the reader expects -- the
    # Native query() path is untouched, so there is no second scan.
    from snuba.clickhouse.pool import ClickhouseReader

    class FakeFormattedQuery:
        def get_sql(self) -> str:
            return "SELECT project_id, count() FROM t GROUP BY project_id WITH TOTALS"

    client = mock.Mock()
    # JSONCompact returns each row (and the totals row) as a positional array.
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "project_id", "type": "UInt64"},
                {"name": "count()", "type": "UInt64"},
            ],
            "data": [[1, 10], [2, 20]],
            "totals": [0, 30],
        }
    ).encode()

    pool = _make_pool(client)
    reader = ClickhouseReader(cache_partition_id=None, client=pool, query_settings_prefix=None)

    result = reader.execute(cast(FormattedQuery, FakeFormattedQuery()), with_totals=True)

    # The trailing totals row is split out as totals; only the real rows remain.
    assert result["data"] == [
        {"project_id": 1, "count()": 10},
        {"project_id": 2, "count()": 20},
    ]
    assert result["totals"] == {"project_id": 0, "count()": 30}
    # Single request via JSONCompact; the Native query() path is never used.
    client.query.assert_not_called()
    _, kwargs = client.raw_query.call_args
    assert kwargs["fmt"] == "JSONCompact"
    assert kwargs["settings"]["output_format_json_quote_64bit_integers"] == 0


def test_totals_jsoncompact_uses_original_query_id_and_inherits_settings() -> None:
    # The single JSONCompact request uses the query's own id and inherits its settings.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "g", "type": "UInt64"}, {"name": "s", "type": "UInt64"}],
            "data": [[1, 10]],
            "totals": [0, 10],
        }
    ).encode()

    pool = _make_pool(client)
    pool.execute_with_totals(
        "SELECT g, sum(v) AS s FROM t GROUP BY g WITH TOTALS",
        query_id="abc-123",
        settings={"max_execution_time": 30},
    )

    _, kwargs = client.raw_query.call_args
    assert kwargs["fmt"] == "JSONCompact"
    assert kwargs["settings"]["query_id"] == "abc-123"
    assert kwargs["settings"]["max_execution_time"] == 30


def test_execute_with_totals_honors_capture_trace() -> None:
    # Reader forwards capture_trace into execute_with_totals; WITH TOTALS must set
    # send_logs_level=trace the same way the plain JSONCompact path does.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "g", "type": "UInt64"}, {"name": "s", "type": "UInt64"}],
            "data": [[1, 10]],
            "totals": [0, 10],
        }
    ).encode()

    pool = _make_pool(client)
    pool.execute_with_totals(
        "SELECT g, sum(v) AS s FROM t GROUP BY g WITH TOTALS",
        capture_trace=True,
    )

    _, kwargs = client.raw_query.call_args
    assert kwargs["settings"]["send_logs_level"] == "trace"


def test_totals_jsoncompact_decodes_value_types() -> None:
    # JSONCompact values decode to the expected Python types. Covers DateTime
    # (string -> datetime so the reader can ISO-format it), Array, and Nullable.
    from snuba.clickhouse.pool import ClickhouseReader

    class FakeFormattedQuery:
        def get_sql(self) -> str:
            return "SELECT g, ts, cnt, arr, opt FROM t GROUP BY g WITH TOTALS"

    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "g", "type": "UInt64"},
                {"name": "ts", "type": "DateTime"},
                {"name": "cnt", "type": "UInt64"},
                {"name": "arr", "type": "Array(UInt64)"},
                {"name": "opt", "type": "Nullable(UInt64)"},
            ],
            "data": [[1, "2023-01-02 03:04:05", 10, [1, 2], None]],
            "totals": [0, "1970-01-01 00:00:00", 10, [1, 2], 5],
        }
    ).encode()

    pool = _make_pool(client)
    reader = ClickhouseReader(cache_partition_id=None, client=pool, query_settings_prefix=None)
    result = reader.execute(cast(FormattedQuery, FakeFormattedQuery()), with_totals=True)

    row = result["data"][0]
    # DateTime string -> datetime -> ISO string via the reader's transform.
    assert row["ts"] == "2023-01-02T03:04:05+00:00"
    assert row["arr"] == [1, 2]
    assert row["opt"] is None
    totals = result["totals"]
    assert totals["ts"] == "1970-01-01T00:00:00+00:00"
    assert totals["cnt"] == 10
    assert totals["opt"] == 5


def test_coerce_temporal_only_touches_date_and_datetime() -> None:
    # Date/DateTime strings become objects (else the reader's transforms crash on a
    # str); Nullable is unwrapped; every other type passes through untouched.
    from snuba.clickhouse.connect import _coerce_temporal

    assert _coerce_temporal("2023-01-02 03:04:05", "DateTime") == datetime(2023, 1, 2, 3, 4, 5)
    assert _coerce_temporal("2023-01-02 03:04:05", "DateTime('UTC')") == datetime(
        2023, 1, 2, 3, 4, 5
    )
    assert _coerce_temporal("2023-01-02", "Date") == date(2023, 1, 2)
    # Parametrized variants reduce to the base type (DateTime64(9), Date32).
    assert _coerce_temporal("2023-01-02 03:04:05.123456789", "DateTime64(9)") == datetime(
        2023, 1, 2, 3, 4, 5, 123456
    )
    assert _coerce_temporal("2023-01-02", "Date32") == date(2023, 1, 2)
    assert _coerce_temporal("2023-01-02 03:04:05", "Nullable(DateTime)") == datetime(
        2023, 1, 2, 3, 4, 5
    )
    # Non-temporal values and non-strings (incl. None) pass through untouched.
    assert _coerce_temporal(5, "UInt64") == 5
    assert _coerce_temporal(1.5, "Float64") == 1.5
    assert _coerce_temporal(None, "Nullable(DateTime)") is None
    assert _coerce_temporal(0, "DateTime") == 0


def test_empty_typed_select_uses_single_jsoncompact_request() -> None:
    # Typed empty SELECTs must not scan twice. JSONCompact is the primary path
    # when with_column_types=True, so meta is present on the first response.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "flags_key", "type": "String"},
                {"name": "count", "type": "UInt64"},
            ],
            "data": [],
        }
    ).encode()

    pool = _make_pool(client)
    result = pool.execute(
        "SELECT flags_key, count() AS count FROM t GROUP BY flags_key",
        with_column_types=True,
    )

    assert result.results == []
    assert result.meta == [("flags_key", "String"), ("count", "UInt64")]
    client.query.assert_not_called()
    client.raw_query.assert_called_once()
    assert client.raw_query.call_args.kwargs["fmt"] == "JSONCompact"


def test_empty_with_totals_returns_meta_and_totals_via_jsoncompact() -> None:
    # A zero-row WITH TOTALS loses its header and totals row over Native/HTTP, but
    # the JSONCompact request still carries both.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "g", "type": "UInt64"}, {"name": "s", "type": "UInt64"}],
            "data": [],
            "totals": [0, 0],
        }
    ).encode()

    pool = _make_pool(client)
    # The trailing totals row is appended to results; the reader pops it off.
    result = pool.execute_with_totals(
        "SELECT g, sum(v) AS s FROM t WHERE g = 999 GROUP BY g WITH TOTALS",
    )

    assert result.meta == [("g", "UInt64"), ("s", "UInt64")]
    assert result.results == [(0, 0)]
    client.query.assert_not_called()


def test_typed_select_uses_single_jsoncompact_request() -> None:
    # Common read path with column types: one JSONCompact request, never Native
    # followed by a meta refetch.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "a", "type": "UInt8"},
                {"name": "b", "type": "UInt8"},
            ],
            "data": [[1, 2]],
        }
    ).encode()

    pool = _make_pool(client)
    result = pool.execute("SELECT a, b FROM t", with_column_types=True)

    assert result.meta == [("a", "UInt8"), ("b", "UInt8")]
    assert result.results == [(1, 2)]
    client.query.assert_not_called()
    client.raw_query.assert_called_once()
    assert client.raw_query.call_args.kwargs["fmt"] == "JSONCompact"


def test_typed_select_applies_client_query_limit() -> None:
    # raw_query does not apply query_limit; typed JSONCompact reads must.
    client = mock.Mock()
    client.query_limit = 10000
    client.raw_query.return_value = json.dumps(
        {"meta": [{"name": "x", "type": "UInt8"}], "data": [[1]]}
    ).encode()

    pool = _make_pool(client)
    pool.execute("SELECT 1", with_column_types=True, query_limit=10000)

    sql = client.raw_query.call_args.args[0]
    assert sql.endswith("LIMIT 10000")
    client.query.assert_not_called()


def test_typed_select_keeps_existing_limit() -> None:
    client = mock.Mock()
    client.query_limit = 10000
    client.raw_query.return_value = json.dumps(
        {"meta": [{"name": "x", "type": "UInt8"}], "data": [[1]]}
    ).encode()

    pool = _make_pool(client)
    pool.execute("SELECT 1 LIMIT 5", with_column_types=True)

    sql = client.raw_query.call_args.args[0]
    assert "LIMIT 5" in sql
    assert "LIMIT 10000" not in sql


def test_connect_type_names_drive_reader_transforms() -> None:
    # The connect pool exposes clickhouse-connect's column_type.name in the
    # result meta, and the driver-agnostic ClickhouseReader runs that through
    # the same Date / DateTime / UUID regex transforms used for the
    # driver. This pins that clickhouse-connect's type-name format matches what
    # those regexes expect (including parametrized types like DateTime('UTC')
    # and Nullable(UUID)), so transformations are not silently skipped on the
    # HTTP path.

    from clickhouse_connect.datatypes.registry import get_from_name

    from snuba.clickhouse.pool import ClickhouseReader

    class FakeFormattedQuery:
        def get_sql(self) -> str:
            return "SELECT d, dt, dt_tz, uid, nuid"

    # Column types named exactly as clickhouse-connect produces them. The
    # assertion documents that clickhouse-connect uses the canonical ClickHouse
    # type strings, so the reader regexes
    # match identically for both drivers.
    col_types = [
        get_from_name("Date"),
        get_from_name("DateTime"),
        get_from_name("DateTime('UTC')"),
        get_from_name("UUID"),
        get_from_name("Nullable(UUID)"),
    ]
    assert [c.name for c in col_types] == [
        "Date",
        "DateTime",
        "DateTime('UTC')",
        "UUID",
        "Nullable(UUID)",
    ]

    client = mock.Mock()
    # Reader always requests column types, so the connect pool uses JSONCompact.
    client.raw_query.return_value = json.dumps(
        {
            "meta": [
                {"name": "d", "type": "Date"},
                {"name": "dt", "type": "DateTime"},
                {"name": "dt_tz", "type": "DateTime('UTC')"},
                {"name": "uid", "type": "UUID"},
                {"name": "nuid", "type": "Nullable(UUID)"},
            ],
            "data": [
                [
                    "2023-01-02",
                    "2023-01-02 03:04:05",
                    "2023-01-02 03:04:05",
                    "00000000-0000-0000-0000-000000000001",
                    "00000000-0000-0000-0000-000000000001",
                ]
            ],
        }
    ).encode()

    pool = _make_pool(client)
    reader = ClickhouseReader(cache_partition_id=None, client=pool, query_settings_prefix=None)
    result = reader.execute(cast(FormattedQuery, FakeFormattedQuery()))

    # Date/DateTime (incl. the parametrized tz variant) become ISO strings and
    # UUID (incl. Nullable) becomes a string. Had the regexes failed to match
    # the connect type names, these would still be the original objects.
    row = result["data"][0]
    assert row["d"] == "2023-01-02T00:00:00+00:00"
    assert row["dt"] == "2023-01-02T03:04:05+00:00"
    assert row["dt_tz"] == "2023-01-02T03:04:05+00:00"
    assert row["uid"] == "00000000-0000-0000-0000-000000000001"
    assert row["nuid"] == "00000000-0000-0000-0000-000000000001"
    client.query.assert_not_called()


def test_execute_explain_uses_command_and_returns_text_rows() -> None:
    # execute_explain serves EXPLAIN via command() -- which sends the statement
    # verbatim, no "FORMAT Native" appended -- not the Native query() path.
    # query() would append "FORMAT Native", the inner query swallows it, and the
    # EXPLAIN output returns as text that the Native reader misparses (the
    # snuba-admin "Unrecognized ClickHouse type base: essionList ..." failure, a
    # fragment of the EXPLAIN AST dump read as a column type). command() returns
    # the decoded text, exposed as one single-column row per line.
    client = mock.Mock()
    # command() strips the trailing newline and (no tabs) returns the whole dump
    # as a single string.
    client.command.return_value = (
        "SelectWithUnionQuery (children 1)\n"
        " ExpressionList (children 1)\n"
        "  Identifier query\n"
        " TablesInSelectQuery (children 1)"
    )

    pool = _make_pool(client)
    result = pool.execute_explain("EXPLAIN AST SELECT query FROM system.clusters")

    # Used the text command() path, never the Native query() path.
    client.command.assert_called_once()
    client.query.assert_not_called()

    # One single-column row per explain line, indentation preserved -- the shape
    # the expected EXPLAIN shape.
    assert result.results == [
        ("SelectWithUnionQuery (children 1)",),
        (" ExpressionList (children 1)",),
        ("  Identifier query",),
        (" TablesInSelectQuery (children 1)",),
    ]
    assert result.meta == [("explain", "String")]


def test_execute_does_not_route_explain_to_command() -> None:
    # The EXPLAIN handling lives behind the dedicated execute_explain() entry
    # point; the generic execute() does not sniff query text. Even an EXPLAIN
    # passed to execute() goes through the typed JSONCompact path -- callers that
    # need EXPLAIN over HTTP must use execute_explain instead.
    client = mock.Mock()
    client.raw_query.return_value = json.dumps(
        {
            "meta": [{"name": "x", "type": "UInt8"}],
            "data": [[1]],
        }
    ).encode()

    pool = _make_pool(client)
    pool.execute("EXPLAIN AST SELECT 1", with_column_types=True)

    client.raw_query.assert_called_once()
    client.query.assert_not_called()
    client.command.assert_not_called()


def test_execute_explain_empty_output_returns_no_rows() -> None:
    # An empty response body makes command() return a QuerySummary (here stubbed
    # by a bare Mock, which is neither str/int/list): that must yield zero rows,
    # not a single empty-string row.
    client = mock.Mock()
    client.command.return_value = mock.Mock()  # stand-in for QuerySummary

    pool = _make_pool(client)
    result = pool.execute_explain("EXPLAIN AST SELECT 1")

    assert result.results == []
    assert result.meta == [("explain", "String")]


def test_execute_explain_error_wrapped_and_preserves_code() -> None:
    # Errors from the command() path must be wrapped in a snuba ClickhouseError
    # with the server code preserved -- the system-query validator relies on the
    # code (e.g. UNKNOWN_TABLE) to turn a failed EXPLAIN into a clean rejection.
    from clickhouse_connect.driver.exceptions import DatabaseError

    UNKNOWN_TABLE = 60
    client = mock.Mock()
    client.command.side_effect = DatabaseError("no such table", code=UNKNOWN_TABLE)

    pool = _make_pool(client)
    try:
        pool.execute_explain("EXPLAIN AST SELECT * FROM nope")
        raise AssertionError("expected a ClickhouseError to be raised")
    except ClickhouseError as error:
        assert error.code == UNKNOWN_TABLE


def test_execute_explain_wraps_client_init_errors() -> None:
    # _new_client() opens the connection on first use and can raise on an
    # unreachable host. Like the normal execute() path, execute_explain must run
    # it inside the error-translation context, so the failure surfaces as a snuba
    # ClickhouseError rather than a raw clickhouse-connect error -- the
    # system-query validator's error handling relies on that contract.
    from clickhouse_connect.driver.exceptions import OperationalError

    pool = _make_pool(mock.Mock())
    pool._new_client = mock.Mock(  # type: ignore[method-assign]
        side_effect=OperationalError("connection refused")
    )

    with pytest.raises(ClickhouseError):
        pool.execute_explain("EXPLAIN AST SELECT 1")


def test_reader_routes_with_totals_through_execute_with_totals() -> None:
    # The reader routes WITH TOTALS through execute_with_totals (not plain execute),
    # forwarding robust, so each driver handles totals its own way.
    from snuba.clickhouse.pool import ClickhouseReader, ClickhouseResult

    class FakeFormattedQuery:
        def get_sql(self) -> str:
            return "SELECT g, sum(v) AS s FROM t GROUP BY g WITH TOTALS"

    pool = mock.Mock()
    pool.execute_with_totals.return_value = ClickhouseResult(
        results=[(1, 10), (0, 10)],
        meta=[("g", "UInt64"), ("s", "UInt64")],
    )

    reader = ClickhouseReader(cache_partition_id=None, client=pool, query_settings_prefix=None)
    result = reader.execute(
        cast(FormattedQuery, FakeFormattedQuery()), with_totals=True, robust=True
    )

    pool.execute_with_totals.assert_called_once()
    _, kwargs = pool.execute_with_totals.call_args
    assert kwargs["robust"] is True
    # The non-totals path (plain execute / execute_robust) is not taken.
    pool.execute.assert_not_called()
    pool.execute_robust.assert_not_called()
    # The trailing totals row is split out; only the real rows remain as data.
    assert result["data"] == [{"g": 1, "s": 10}]
    assert result["totals"] == {"g": 0, "s": 10}


@pytest.mark.clickhouse_db
def test_use_protocol_version_disabled_by_default() -> None:
    from clickhouse_connect import common as clickhouse_connect_common

    assert clickhouse_connect_common.get_setting("use_protocol_version") is False


def test_new_client_per_query() -> None:
    clients = [mock.Mock(name=f"c{i}") for i in range(3)]
    for c in clients:
        c.query.return_value = FakeQueryResult(result_set=[[1]])
    pool = ClickhouseConnectPool(host="h", user="u", password="p", database="d")
    pool._new_client = mock.Mock(side_effect=clients)  # type: ignore[method-assign]
    pool.execute("SELECT 1")
    pool.execute("SELECT 2")
    pool.execute("SELECT 3")
    assert pool._new_client.call_count == 3


def test_shared_socket_pool() -> None:
    import snuba.clickhouse.connect as connect_mod

    connect_mod._pool_managers.clear()
    with (
        mock.patch("snuba.clickhouse.connect.get_pool_manager") as gpm,
        mock.patch("clickhouse_connect.get_client") as get_client,
    ):
        shared = mock.Mock(name="pool")
        gpm.return_value = shared
        get_client.return_value = mock.Mock()
        a = ClickhouseConnectPool(host="h", user="u", password="p", database="d")
        b = ClickhouseConnectPool(host="other", user="u", password="p", database="d")
        a._new_client()
        b._new_client()
        assert gpm.call_count == 1
        assert get_client.call_args_list[0].kwargs["pool_mgr"] is shared
        assert get_client.call_args_list[1].kwargs["pool_mgr"] is shared
    connect_mod._pool_managers.clear()


def test_response_is_drained() -> None:
    client = mock.Mock()
    result = mock.Mock()
    result.summary = {}
    result.result_set = [[1]]
    result.column_names = ()
    result.column_types = ()
    client.query.return_value = result
    _make_pool(client).execute("SELECT 1")
    result.close.assert_called_once()


def test_response_is_drained_on_error() -> None:
    client = mock.Mock()
    result = mock.Mock()
    result.summary = {}
    type(result).result_set = mock.PropertyMock(side_effect=RuntimeError("boom"))
    client.query.return_value = result
    with pytest.raises(RuntimeError):
        _make_pool(client).execute("SELECT 1")
    result.close.assert_called_once()


def test_operational_error_mapped() -> None:
    from clickhouse_connect.driver.exceptions import OperationalError

    client = mock.Mock()
    client.query.side_effect = OperationalError("conn reset")
    with pytest.raises(ClickhouseError) as excinfo:
        _make_pool(client).execute("SELECT 1")
    assert excinfo.value.code == -1


def test_stream_failure_mapped() -> None:
    from clickhouse_connect.driver.exceptions import StreamFailureError

    client = mock.Mock()
    client.query.side_effect = StreamFailureError("stream died")
    with pytest.raises(ClickhouseError) as excinfo:
        _make_pool(client).execute("SELECT 1")
    assert excinfo.value.code == -1


def test_shared_pools_reset_after_fork() -> None:
    from clickhouse_connect.driver.httputil import all_managers

    import snuba.clickhouse.connect as connect_mod

    connect_mod._close_pools()
    mgr = mock.Mock()
    all_managers[mgr] = 0
    connect_mod._pool_managers[(None, False)] = mgr

    connect_mod._reset_pools_after_fork()

    assert connect_mod._pool_managers == {}
    assert mgr not in all_managers
    mgr.clear.assert_not_called()


def test_close_pools_releases_sockets() -> None:
    from clickhouse_connect.driver.httputil import all_managers

    import snuba.clickhouse.connect as connect_mod

    connect_mod._close_pools()
    mgr = mock.Mock()
    all_managers[mgr] = 0
    connect_mod._pool_managers[(None, False)] = mgr

    connect_mod._close_pools()

    mgr.clear.assert_called_once()
    assert mgr not in all_managers
    assert connect_mod._pool_managers == {}
