name: arm64
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # For now, we cannot build linux/arm64 images on Linux hosts since
  # |docker buildx ls| does not list arm64 as an option.
  #
  # This step does not have a set timeout because it is very slow. This is due
  # because emulation required (this is running on an Intel host rather than an arm64 host)
  # and that many Python packages do not have arm wheels, thus, requirying to build them from source.
  # Upgrading Python package versions + giving access to a cache could improve things a lot
  snuba-arm64-image:
    name: "Docker Arm64 build"
    runs-on: macos-11
    env:
      # `sentry devservices up snuba` picks up the `amd64` version of the image
      # For now, we will publish to a different name until we want to officially
      # support the image on Docker Hub
      # NOTE: This image has only been tested for local development
      SNUBA_IMAGE: ghcr.io/getsentry/snuba-arm64-dev
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Get branch name
        id: branch
        # strip `refs/heads/` from $GITHUB_REF and replace `/` with `-` so that
        # it can be used as a docker tag
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

      - name: Set up Docker
        run: |
          brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done

      - name: Registry login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull snuba CI images
        run: |
          docker pull ${SNUBA_IMAGE}:${{ steps.branch.outputs.branch }} || \
            docker pull ${SNUBA_IMAGE}:latest || true

      - name: Create Image
        run: |
          docker buildx create --name arm64-builder --use
          docker buildx build --platform linux/arm64 \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ${SNUBA_IMAGE}:latest \
            --cache-from ${SNUBA_IMAGE}:${{ steps.branch.outputs.branch }} \
            -t ${SNUBA_IMAGE}:latest \
            -t ${SNUBA_IMAGE}:${{ steps.branch.outputs.branch }} \
            -t ${SNUBA_IMAGE}:${{ github.sha }} \
            --load .

      - name: Publish
        # Forks cannot push to the getsentry org
        if: github.repository_owner == 'getsentry'
        run: |
          # Useful to speed up PRs
          docker push ${SNUBA_IMAGE}:${{ steps.branch.outputs.branch }}
          if [ "${{ steps.branch.outputs.branch }}" == 'master' ]; then
            # Useful for regression testing on Sentry's checkout
            docker push ${SNUBA_IMAGE}:${{ github.sha }}
            # The latest tag should only be published on `master`
            docker push ${SNUBA_IMAGE}:latest
          fi
