name: docker arm64
on:
  push:
    branches:
      - master
  # XXX: Temp
  pull_request:

jobs:
  linting:
    name: "Docker Arm64"
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      # Unbuntu 20
      # Docker version 20.10.9+azure-1, build c2ea9bc90bacf19bdbe37fd13eec8772432aca99
      # github.com/docker/buildx 0.6.3+azure 266c0eac611d64fcc0c72d80206aa364e826758d
      #
      # Mac 11
      # Docker version 20.10.8, build 3967b7d
      # github.com/docker/buildx v0.6.3 266c0eac611d64fcc0c72d80206aa364e826758d
      #
      # Docker Buildx is included in Docker Desktop and Docker Linux packages when installed using the DEB or RPM packages.
      - name: Docker
        run: |

          if [ $(uname) == 'Darwin' ]; then
            brew install --cask docker
            sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
            open -a /Applications/Docker.app --args --unattended --accept-license
            echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
            while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
          else
            curl -Ls https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-arm64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x  ~/.docker/cli-plugins/docker-buildx
          fi
          set -x
          docker --version
          which docker
          ls -l $(which docker)
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx version
          docker buildx ls
          docker buildx create --name mybuilderFoo --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 -t getsnuba/snuba:buildx-test .
          docker buildx imagetools inspect getsnuba/snuba:buildx-test
