name: docker arm64
on:
  push:
    branches:
      - master
  # XXX: Temp
  pull_request:

jobs:
  linting:
    name: "Docker Arm64"
    timeout-minutes: 2
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Docker
        run: |
          set -x
          docker --version
          docker buildx version
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 -t getsnuba/snuba:buildx-test .
          docker buildx imagetools inspect getsnuba/snuba:buildx-test
