name: Enforce License Compliance

on:
  push:
    branches: [master, main, release/*]
  pull_request:
    branches: [master, main]

jobs:
  enforce-license-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 'Enforce License Compliance'
        uses: getsentry/action-enforce-license-compliance@6599a041195852debba3417e069829060d671e76
        with:
          fossa_api_key: ${{ secrets.FOSSA_API_KEY }}
