name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

labels:
  migrations:
    - snuba/migrations/group_loader.py
    - snuba/migrations/groups.py
    - snuba/snuba_migrations/**/*
    - snuba/migrations/system_migrations/*
