name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust-linting:
    name: "Linting - Rust"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
      - name: Run linter
        run: |
          make lint-rust
