name: Validate Sentry Options Schema

on:
  pull_request:
    paths:
      - 'sentry-options/schemas/**'
      - 'uv.lock'
      - '.github/workflows/validate-sentry-options.yml'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cli-version:
    name: Determine sentry-options CLI version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: uv.lock
          sparse-checkout-cone-mode: false
      - name: Parse sentry-options version from uv.lock
        id: version
        run: |
          echo -n "version=" >> "$GITHUB_OUTPUT"
          yq -p toml -oy '.package[] | select(.name == "sentry-options") | .version' uv.lock >> "$GITHUB_OUTPUT"

  validate-schema:
    needs: cli-version
    name: Validate Schema Evolution
    # main at pin time
    uses: getsentry/sentry-options/.github/workflows/validate-schema.yml@24dbd915e6f091626630a284f9439bf983c32dbe
    secrets:
      SENTRY_INTERNAL_APP_PRIVATE_KEY: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
    with:
      schemas-path: sentry-options/schemas
      cli-version: ${{ needs.cli-version.outputs.version }}
