name: Validate Sentry Options Schema

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: files-changed
    runs-on: ubuntu-latest
    outputs:
      schemas: ${{ steps.changes.outputs.schemas }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Check for relevant file changes
        uses: getsentry/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            schemas:
              - 'sentry-options/schemas/**'

  validate-schema:
    if: needs.files-changed.outputs.schemas == 'true'
    needs: files-changed
    name: Validate Schema Evolution
    uses: getsentry/sentry-options/.github/workflows/validate-schema.yml@0b115be89b102d76beff8106bd4054365954282e
    secrets: inherit
    with:
      schemas-path: sentry-options/schemas
